### ISSUE TITLE
Feature request: Notify on no available username

### ISSUE THREAD

**Issue by bendoin** [squidowl/halloy#112]
When starting Halloy with a config.yaml from the template the application connected and disconnected without telling me why.

Found out that the problem was no available nickname in the `~/.var/app/org.squidowl.halloy/data/halloy/halloy.log` file.

Related to https://github.com/squidowl/halloy/issues/76 in a "general user error/warning" way, this could also possibly be printed directly in the application for faster user feedback?

**Comment by tarkah** [comment]
Yeah I believe there are some `NOTIFY` to target `AUTH` related messages we aren't printing right now. I believe @casperstorm is looking into this atm. Thanks for the report!
