### ISSUE TITLE
Cursor blink should stop (or disappear) when window no longer in focus

### ISSUE THREAD

**Issue by Daeraxa** [squidowl/halloy#124]
At the moment if I have a Halloy window open and click in a chat, the text cursor in the "Send Message..." text box blinks.

If I then focus a different window, the cursor keeps blinking - most apps will stop cursor blink if the window is no longer in focus to show that text will not be inserted.

**Comment by tarkah** [comment]
Lol I was just noticing this

**Comment by tarkah** [comment]
I'll look at fixing this upstream with `iced`. Thanks for the report!

**Comment by tarkah** [comment]
I've submitted the fix upstream https://github.com/iced-rs/iced/pull/1955
