### ISSUE TITLE
irc lines shouldn't go beyond 512 bytes

### ISSUE THREAD

**Issue by ineeee** [squidowl/halloy#128]
right now its possible to send lines which exceed rfc1459's `510 bytes + CRLF`, which means messages appear to go through but they get cut off by the irc daemon.

i think there is a irc command (`003` or `004`?) that tells the client the max length of irc lines, but maybe it was for channel names or something like that.

environment: halloy 2023.2, windows 10, rizon via znc.

**Comment by ineeee** [comment]
by the way, sorry about making so many issues. i want this irc client to succeed, so i've been testing it quite a bit. unfortunately i don't know any rust at all and im a bit busy, so i can't really get into fixing things myself (can i use rustc in windows?).

**Comment by casperstorm** [comment]
> by the way, sorry about making so many issues. i want this irc client to succeed, so i've been testing it quite a bit. unfortunately i don't know any rust at all and im a bit busy, so i can't really get into fixing things myself (can i use rustc in windows?).
> 
> 

Don't feel sorry. We thank you for all these issues. It's amazing to get feedback like this.

You can indeed install rust on windows but know just by creating these issues you are contributing!
