### ISSUE TITLE
Please can you send me that awesome wallpaper used in the showcase video?

### ISSUE THREAD

**Issue by ItsTerm1n4l** [squidowl/halloy#129]
Hi, I know its not really an issue but please could you link me the wallpaper you used in the showcase video, it looks really cool.

**Comment by casperstorm** [comment]
I added a section in the wiki for wallpapers that goes well with Halloy.
You can find the requested wallpaper there.

https://github.com/squidowl/halloy/wiki/Wallpapers

**Comment by ItsTerm1n4l** [comment]
thank you.

**Comment by Icy-Thought** [comment]
Do you still have that wiki page available somewhere because I cannot seem to find it in this repository.

**Comment by casperstorm** [comment]
Here you go, @Icy-Thought.

![singularity-3840×2160](https://github.com/user-attachments/assets/73f91a6b-508d-4de9-bf43-ee8a2c6f272b)

**Comment by Icy-Thought** [comment]
That wallpaper was cooler than I'd assumed it to be! Thanks!
