### ISSUE TITLE
Whois only goes to channel window if channel has focus

### ISSUE THREAD

**Issue by smakkerlak** [squidowl/halloy#132]
Halloy 2023.2

Doing whois on a user in a window that is not "selected" will send whois to server window.
It should probably go to the window where the whois was performed, no matter the window focus.

**Comment by tarkah** [comment]
Thanks for the report! 

If your server supports the `labeled-response` extension, this is fixed via #140.

If not, I'll look at implementing a better fix so we track the buffer who sent the whois request and associate that with all responses until the ENDWHOIS. This is somewhat error prone if you somehow can initiate 2 different whois from 2 different buffers before the first fully returns. But this is very very unlikely unless you have terrible ping times to the server and are an extremely fast clicker, lol.  But it's the best we will be able to do without `labeled-response`
