### ISSUE TITLE
Display message sent from other clients

### ISSUE THREAD

**Issue by Zstorm999** [squidowl/halloy#133]
Hello 

I have a bouncer (soju) setup for multiple clients: one on my desktop and one on my phone. Messages I send from my phone are never displayed inside halloy, even though they are received by the client (I checked with wireshark and the packet is received on my desktop).

In short, 
on another client, I can see all my messages from all clients
on halloy, I can only see my messages sent from halloy

Any idea where this might come from ?

**Comment by tarkah** [comment]
Can you please run Halloy with RUST_LOG=trace and check the log file on your desktop to see if it's receiving the message and what the message is?

**Comment by ineeee** [comment]
i can confirm this issue, i can't see my own messages from znc in halloy

**Comment by tarkah** [comment]
I have znc setup so I'll be able to test this, thanks for the report!

I'm assuming it's because we don't negotiate the `echo-message` IRC extension which the bouncers probably ensure the client supports before broadcasting them back downstream.

**Comment by tarkah** [comment]
> i can confirm this issue, i can't see my own messages from znc in halloy

I can't recreate this issue from ZNC. If I connect to the same user on two different clients (halloy & textual), and I send a message on textual, I see it on halloy.

**Comment by Daeraxa** [comment]
> I can't recreate this issue from ZNC. If I connect to the same user on two different clients (halloy & textual), and I send a message on textual, I see it on halloy.

Same here:

- Connected to my ZNC on Halloy
- Connected to my ZNC on mobile (Revolution IRC)
- Sent message from mobile
  - Appears in Halloy and mobile
- Sent message from Halloy
  - Appears in Halloy and mobile

![image](https://github.com/squidowl/halloy/assets/58074586/40c0eb66-707a-49d8-9b76-df98542d5cce)

**Comment by tarkah** [comment]
@Zstorm999 can you try building / testing against #140 and see if this is fixed? I need to setup my own soju instance to test myself.

**Comment by tarkah** [comment]
@Zstorm999 disregarding #140 I just tested `soju` off  `2023.2` on two separate instances of halloy and had no issues seeing my own sent messages in both clients. Are you maybe on an old version of `soju`?

**Comment by Zstorm999** [comment]
I tested on #140 and it did not fix my problem and now I don’t see my messages in the other direction as well. I did not setup `soju` myself, a friend of mine did it for me so I’ll check with them to see if it could come from there.

**Comment by tarkah** [comment]
> I tested on #140 and it did not fix my problem and now I don’t see my messages in the other direction as well. I did not setup `soju` myself, a friend of mine did it for me so I’ll check with them to see if it could come from there. 

You can't see the sent messages in Halloy now either?

**Comment by Zstorm999** [comment]
> > I tested on #140 and it did not fix my problem and now I don’t see my messages in the other direction as well. I did not setup `soju` myself, a friend of mine did it for me so I’ll check with them to see if it could come from there. 
> 
> You can't see the sent messages in Halloy now either?

Exactly, so I believe it to be a problem on my bouncer rather than halloy.

I will investigate further tonight if I get the time.
