### ISSUE TITLE
ram usage (...?)

### ISSUE THREAD

**Issue by ineeee** [squidowl/halloy#135]
i just noticed that halloy's ram usage is insane. i was killing another random process and noticed halloy is using 459 mb of ram. is that normal? i don't remember it happening on 2023.1-alpha1.

attached is a screenshot of task manager:
![image](https://github.com/squidowl/halloy/assets/10874672/24bf1ecd-6e32-474e-a42c-dbb48463c75e)

i thought this was related to my bouncer's buffer sizes, so i left some channels and sent `/msg *status ClearAllBuffers` then restarted the client, however the ram usage stays around the same even with 6 empty channels.

i run windows 10, halloy 2023.2 and i'm connected to rizon via znc.

**Comment by Daeraxa** [comment]
On Linux I've had it open for a while but I'm only on 85.4MB built from the latest commit.

**Comment by ineeee** [comment]
after deleting the history folder (`$config/halloy/history/`) and restarting, ram usage went down by half.

![image](https://github.com/squidowl/halloy/assets/10874672/1291e4e8-a3ac-4dae-967d-61ca0e844aa3)

**Comment by tarkah** [comment]
> after deleting the history folder (`$config/halloy/history/`) and restarting, ram usage went down by half.
> 
> ![image](https://github.com/squidowl/halloy/assets/10874672/1291e4e8-a3ac-4dae-967d-61ca0e844aa3)
> 

We keep up to the last 10,000 messages. This is probably way too high or we can make it configurable.

We only keep the full history in memory for opened buffers so closed buffers should never impact memory usage.

As for the rest of the memory usage, a lot of it comes from the wgpu renderer backend that's used. So this might partly be a directx / driver issue on windows. You can test out the software renderer by using env var `ICED_BACKED=tiny-skia` to confirm that it goes way down.

**Comment by ineeee** [comment]
changing to the software renderer increased memory usage to ~300mb, but the font rendering looks awful (no antialising?) so i'll stick with the other one.

it would be nice to be able to change the buffer size, since i treat irc like an ephemeral messaging platform-ish so i don't care about past history.

either way i can waste a bit of ram 😅

**Comment by tarkah** [comment]
> changing to the software renderer increased memory usage to ~300mb, but the font rendering looks awful (no antialising?) so i'll stick with the other one.

Interesting! I've mostly tested on Linux so that's where I've seen the big difference in usage between software renderer and Vulkan (wgpu uses Vulkan on linux), with Vulkan using much more memory. 



> it would be nice to be able to change the buffer size, since i treat irc like an ephemeral messaging platform-ish so i don't care about past history.

Agreed, we can make this configurable 👍

**Comment by tarkah** [comment]
I've confirmed the underlying issue to RAM usage. See the below heaptrack of app memory consumption.

The bottom two stacks are all related to text caching (span & layout caching) that our text backend is doing. The 3rd stack from the bottom (3rd largest) is from the font file we load into memory. When you remove these, our actual memory usage is closer to ~30MB. This was after I opened multiple buffers with 10k messages each. Message history uses at most 3-6 MB of RAM even with multiple buffers of 10k messages open.

So this is basically down to how our GUI framework [iced](https://github.com/iced-rs/iced) is doing text caching. All iced applications then are currently impacted by this same issue (on both gpu accelerated and software renderer backends). I'd imagine other frameworks might benefit from using system level APIs for text so they don't incur this memory penalty but I am not sure. 

As text handling isn't quite mature within the Rust ecosystem and definitely not iced, I expect this will improve in the future. I'll look to see if there's ways to optimize the caching that haven't already been explored. 

![image](https://github.com/squidowl/halloy/assets/10239377/c918e674-6df8-4c1e-8a8b-0d0b9c539289)

**Comment by hecrj** [comment]
@tarkah Let me cook.

**Comment by ineeee** [comment]
hi, posting more info since it was closed.

![image](https://github.com/user-attachments/assets/3af21e63-9013-403b-a83a-44061bd440cc)


now uses ~144mb of ram on 13 buffers (each with 200+ lines each). seems like a huge improvement to me 👍  halloy 2024.8 on windows 10.
