### ISSUE TITLE
Feature request: Config wizard

### ISSUE THREAD

**Issue by Daeraxa** [squidowl/halloy#137]
Was just musing that instead of using the `config.template.yaml` maybe Halloy could provide a basic config via a wizard instead.

A couple of benefits I can see to that approach:

- More "first time" user friendly - not just to Halloy but to IRC in general as this does seem to be generating some interest in people who haven't really used IRC before
- No more "halloy" users (does this cause a clash if two `halloy` users try to connect?)
- More likely to get users onto it quickly rather than being turned away by having to edit a config file.

As a very quick (non functional) UI mockup:

## Initial welcome

![image](https://github.com/squidowl/halloy/assets/58074586/ae21ed47-950c-4a1d-b05e-dc0b205887b2)

## Config wizard

![image](https://github.com/squidowl/halloy/assets/58074586/f118217a-b6ce-408b-ab05-3652682291e5)

Some of the fields would/could be auto filled (particularly the server, channels and theme) but the nickname would be empty and would have to be mandatory.

**Comment by casperstorm** [comment]
This is a good idea on paper, but out of scope for Halloy.
We (@tarkah and I) have decided that we either do:
1. All UI for configuration
2. All config file for configuration

If we start mixing we will fall behind our goal which is simply to be an awesome irc client.
We don't want to start spending time on UX and settings screens when we can do features and better chatting experience.
Saying this also means we will cut out "users" but I don't believe we can win all battles to begin with.
