### ISSUE TITLE
high resource usage

### ISSUE THREAD

**Issue by alirezaalavi87** [squidowl/halloy#148]
hi guys.
so I started using halloy today, since I liked how it looked and I like rust. (linux - flatpak)
halloy advertises as a lightweight and fast IRC client. when using halloy, I noticed it takes ~140MB ram while pidgin takes ~100MB ram. pidgin also has a lot more features. so what is the advantage of this application if it's not the simplicity and low resource usage? 
I suggest working on getting the app to lower resource usage.

thanks for the great project.

**Comment by casperstorm** [comment]
Majority of memory usage comes from the wgpu renderer backend that's used. That being said we are constantly looking at optimizing memory usage. Performance is something we value greatly. As for features; I am sure most other IRC clients at this point have more features than Halloy! We are barely a month old where Pidgin, as an example, is 24 years old.

Halloy is new project, a new take on how a IRC client built in 2023 would be. It will take time to be competitive to other major clients.

**Comment by alirezaalavi87** [comment]
> Majority of memory usage comes from the wgpu renderer backend that's used. That being said we are constantly looking at optimizing memory usage. Performance is something we value greatly.
 thanks, that's great to hear.

> Halloy is new project, a new take on how a IRC client built in 2023 would be. It will take time to be competitive to other major clients.
that's a great point! I hope it gets better and better.
