### ISSUE TITLE
Colored nicknames

### ISSUE THREAD

**Issue by casperstorm** [squidowl/halloy#15]
It's common that each nickname has it's own color, which helps readability.
For picking the colors we should use `accent` color converted to HSL and then pick a random hue value, while not touching saturation and lightning.

Stretch goals:
 - Caching the color to a file with `nick@host` and invalidated on theme change.
 - Enable/disable colored nicks in channel settings (#6)

**Comment by tarkah** [comment]
I think we can implement without any caching. If we hash nick@host, we can use that as a seed for rng for the hue value and it should be deterministic. Maybe we cache at runtime for performance reasons, but we shouldn't need to persist it to fs

**Comment by casperstorm** [comment]
Thats a great idea!
