### ISSUE TITLE
Feature request: Buffer tiling patterns

### ISSUE THREAD

**Issue by Daeraxa** [squidowl/halloy#155]
At the moment each new buffer you open splits the current pane horizontally.

It would be nice if a page could be taken from tiling window managers and other tiling apps like terminals to support different tiling patterns.

For example `tall` layout:
- Buffer 1 is full screen
- Buffer 2 makes a vertical split
- Buffer 3 makes a horizontal split within buffer 2
- Buffer 4 makes a horizontal split but not within buffer 2 or 3, instead it splits it equally
e.g.
```
┌──────────────┬───────────────┐
│              │               │
│              │       2       │
│              │               │
│              ├───────────────┤
│              │               │
│      1       │       3       │
│              │               │
│              ├───────────────┤
│              │               │
│              │       4       │
│              │               │
└──────────────┴───────────────┘
```
The kitty terminal documentation has some other examples - https://sw.kovidgoyal.net/kitty/layouts/

**Comment by casperstorm** [comment]
I think our setup is currently sufficient and flexible to most needs.
Will close this for now.
