### ISSUE TITLE
Text input box is repeating or entering letters when backspace is held to delete text (see gif...)

### ISSUE THREAD

**Issue by Daeraxa** [squidowl/halloy#160]
Honestly I don't exactly have the right words to explain what is going on here so best just to watch the gif.
To replicate:
- Type a bunch of stuff, the more the better.
- Hold backspace to delete it all
- Random(? possibly reversed order) letters appear behind the cursor

![halloy2](https://github.com/squidowl/halloy/assets/58074586/d6345658-3914-40f6-83ef-d17559740596)

It almost appears like the cursor is getting ahead of the text (i.e. moving a position without a delete operation happening) so is essentially skipping some letters.

**Comment by ineeee** [comment]
backspace works fine for me on windows with the fastest keyboard repeat rate

**Comment by Daeraxa** [comment]
I don't think I've ever changed the repeat rate on mine but it could well be related to the speed of the computer. If I do it on my Linux system (the demo was from Windows) I can still replicate it but far less often and with fewer "skipped" characters.

**Comment by casperstorm** [comment]
I really can't reproduce this on any system - is this sill a bug @Daeraxa?
