### ISSUE TITLE
being kicked while offline leaves a buffer stuck on screen

### ISSUE THREAD

**Issue by ineeee** [squidowl/halloy#161]
if you get kicked from a channel while being offline (your bouncer gets kicked, but your client is offline) then the buffer from that channel will permanently remain open if it was open before the client closed. sorry, this is a bit hard to explain.

steps to reproduce with a bouncer:
1. join a channel, leave the buffer open
2. close the client
3. get kicked from that channel while offline
4. open the client
5. the buffer from the channel will be open, with no way to close it

you can leave the channel if you rejoin it from another channel.

**Comment by ineeee** [comment]
i suppose znc is at fault, since it doesn't send PART to the client

**Comment by casperstorm** [comment]
Is this still a issue @ineeee?

**Comment by ineeee** [comment]
hi, i haven't checked because unfortunately my vps provider is having upstream issues, so i took it as an opportunity to just take a break from irc and the internet in general. i noticed there was a new release (yay!) so i'll try it out during this week maybe.

**Comment by ineeee** [comment]
hi yea still happens. buffer is stuck if the bouncer gets disconnected
