### ISSUE TITLE
Text entry cursor keeps changing size every other letter

### ISSUE THREAD

**Issue by Daeraxa** [squidowl/halloy#162]
As in the title, the width of the cursor changes every other letter (thick then thin etc.)

![Peek 2023-07-16 00-55](https://github.com/squidowl/halloy/assets/58074586/998be640-0af1-46ef-843c-ee10cc2deb62)

Halloy `#1165897` on Linux Mint

**Comment by tarkah** [comment]
We must be rendering it on a half pixel 🧐

**Comment by ineeee** [comment]
why did you make me see this? now im going to notice it every time i'm typing 😭

same on windows using a different theme:

![image](https://github.com/squidowl/halloy/assets/10874672/35de5b86-6cee-4c4e-a1e9-ad5efa77dacc) ![image](https://github.com/squidowl/halloy/assets/10874672/531037df-fb70-42ee-be71-e868d6cd0fc5)

but using `ICED_BACKEND=tiny-skia` it does _not_ show up

**Comment by Daeraxa** [comment]
> why did you make me see this? now im going to notice it every time i'm typing

Honestly no idea how I didn't see it either, its all I can see now too, I wish I hadn't noticed it

**Comment by hecrj** [comment]
This should fix the issue in screens with an integral scale factor (most of the sane ones): https://github.com/iced-rs/iced/pull/2320
