### ISSUE TITLE
Feature request: DCC

### ISSUE THREAD

**Issue by TwinTusks** [squidowl/halloy#164]
I'm wondering if is possible to add DCC function to the app, currently it seems there isn't anyway to receive files.

Thank you.

**Comment by casperstorm** [comment]
Currently the underlying irc crate doesn't support DCC so we would have to fork it and implement it (see: relevant issue https://github.com/aatxe/irc/issues/49). I'll keep this issue open and mark it with appropriate labels. Thanks for reporting.

**Comment by applesaucetf** [comment]
Any update/ ETA on this? Love your client and the work you are doing, but still unable to receive files.

**Comment by ViktorEvil** [comment]
I agree, I love the client but DCC is essential for me

**Comment by casperstorm** [comment]
No ETA, we haven't begun on this feature yet.
We haven't had the biggest request on this feature before now, so haven't prioritized it.

Let me start researching how, and who, has the best UI/UX and see what i can cook up.

**Comment by ViktorEvil** [comment]
Thanks caspestorm, can’t wait to try this
