### ISSUE TITLE
Feature request: Encrypt password or allow storage within keychain

### ISSUE THREAD

**Issue by Daeraxa** [squidowl/halloy#170]
Allow for encryption of password or storage within the OS keychain store.

Main benefit: no more unencrypted passwords stored in a plaintext file but still allows auto-login without needing to verify on the server.

**Comment by tarkah** [comment]
We can definitely interface with the OS keystore, but what would the UX look like to set this up? I think that'll be the biggest blocker for figuring this out.

**Comment by Daeraxa** [comment]
Command bar I reckon, a command to set password.

**Comment by tarkah** [comment]
Just as an FYI, we now support SASL EXTERNAL so you can setup certificate auth w/ the server and your config now points to a cert file. This way you aren't storing any secrets in your config.

**Comment by casperstorm** [comment]
Closing. Recommendation is to use SASL for now.
