### ISSUE TITLE
Connection to servers without cap negotiation is stuck

### ISSUE THREAD

**Issue by vilunov** [squidowl/halloy#171]
This is caused by https://github.com/squidowl/halloy/pull/140 and happens only when connecting to servers which do not support capability negotiation. This is allowed by the [spec](https://ircv3.net/specs/extensions/capability-negotiation.html), in that case the successful connection is indicated by 001-type msg from server.

The correct approach would be to send `CAP LS 302`, `NICK` and `USER` all at the same time without expecting a message in response, and only then handling the appropriate `CAP LS` or a different response.

**Comment by vilunov** [comment]
I will try to fix it later this weekend, unless someone will be faster than me

**Comment by tarkah** [comment]
This is fixed in the `feat/internal-irc` branch in working on. We're moving to our own IRC backend and I ran into this issue w/ quakenet when testing so I've fixed 👍

Thanks for the report.

**Comment by vilunov** [comment]
Oh, that's nice to hear, thanks! You can close the issue then

**Comment by tarkah** [comment]
I'll close it along with the PR, thanks!
