### ISSUE TITLE
Confirmation on license & two crate updates

### ISSUE THREAD

**Issue by Cellesti** [squidowl/halloy#174]
Hi, i am trying to package Halloy for Alpine linux, and would like to confirm if the `<project_license>GPL-3.0+</project_license>` line in `assets/halloy.appdata.xml` means Halloy is licensed under `GPL-3.0-or-later` (as opposed to `GPL-3.0-only`).

It seems the short license identifier `GPL-3.0` has been [deprecated by SPDX](https://spdx.org/licenses/GPL-3.0.html).

Besides that, would it be possible to update these two crates in the next release:
- `getrandom` to `0.2.10` which fixes a [problem with undefined reference to open64](https://github.com/rust-random/getrandom/pull/326) that occurs on musl libc 1.2.4 that Alpine uses.
- `half` to `2.3.1` which fixes [compilation on 32-bit x86](https://github.com/starkat99/half-rs/issues/93).

Thank you.

**Comment by tarkah** [comment]
@Cellesti Thanks for the report!

I've gone ahead and updated those deps, along w/ a `cargo audit` notification about `openssl`. 5241b87a4a0ed84ace72d9a25606e688a6f55564

I've also updated the SPDX identifier to `GPL-3.0-or-later`, which you can use. a24ddb539e35c59b3a64ff45e05b6b707f3a997b

Thanks again!
