### ISSUE TITLE
Request: set window app_id on Wayland

### ISSUE THREAD

**Issue by tranzystorek-io** [squidowl/halloy#181]
I attempted a halloy package build for Void Linux, and after running it on Wayland, the window has no app_id property set which prevents it from being detected by various applications, e.g. Waybar.

**Comment by tarkah** [comment]
Thanks for the report! I just recently upstreamed a fix that'll allow us to properly set the window application id. I'll make sure this is patched for the next release!

**Comment by tarkah** [comment]
@tranzystorek-io If you can build from source `cargo run --release`, can you try #182 and see if this fixes the issue?

**Comment by tranzystorek-io** [comment]
I just built that PR and confirm that the app_id is there and Waybar displays the icon :)

**Comment by tarkah** [comment]
awesome! Thanks for confirming :) I've merged and you can package off of 7347a1f5a86e2404e4b960364ef33c56118d29f2 since this patch basically sits on top of the `2023.3` tag. 

Next actual release will include this.
