### ISSUE TITLE
Halloy badly interacts with Plasma desktop's Klipper context menu

### ISSUE THREAD

**Issue by AndydeCleyre** [squidowl/halloy#194]
I'm using Plasma desktop 5.24.7 with X11 on Pop!_OS with Halloy 2023.3 via flathub, and usually I can open the klipper menu (via keyboard shortcut) and hit enter on an item to replace the clipboard content.

When I do this with Halloy's message field focused, it additionally pastes the content *originally* in the clipboard (it really shouldn't, even if it *were* the newly selected content), and additionally *sends* that former clipboard content as a message (it really, really, REALLY shouldn't).

I think the pasting occurs during the opening of the menu, which I do with ctrl+alt+v (is that the first problem for Halloy?) and the sending of the message happens when I hit Enter on that menu (Halloy isn't focused in that moment, the Klipper menu is).

I've now sent a mix of sensitive and annoying nonsensical messages to different chats due to this.

**Comment by casperstorm** [comment]
That sounds annoying.
It seems to be a upstream issue with https://github.com/iced-rs/iced, which is the GUI framework we use.
Will mark it as upstream and look into it. Thanks for reporting it.

**Comment by casperstorm** [comment]
The text_input isn't processing any keypresses unless the input is focused: https://github.com/iced-rs/iced/blob/cb8b70bec3e8bbf809e7d8ffc559adb712f45e14/widget/src/text_input.rs#L718. I asked @bungoboingo to help test this on Pop to see if she can reproduce any weird interaction with Klipper.

**Comment by tarkah** [comment]
To add to this, the other issue stems from here: 

https://github.com/iced-rs/iced/blob/cb8b70bec3e8bbf809e7d8ffc559adb712f45e14/widget/src/text_input.rs#L844C22-L845

The text input only checks if `cmd / ctrl` is pressed along w/ `v`. It does not validate it's the _only_ modifier, so shift / alt can also be used and it'll still paste.

**Comment by casperstorm** [comment]
Upstream fix to not paste when pressing <kbd>cmd</kbd>+<kbd>alt</kbd>+<kbd>v</kbd>: https://github.com/iced-rs/iced/pull/2006
