### ISSUE TITLE
Resizable Panes

### ISSUE THREAD

**Issue by tstraus13** [squidowl/halloy#197]
Hello,

Love the app. The only thing that bugged me was when I increased the font size the server/channel list pane and the user list pane are too small for the text and the text is no longer legible. It would be nice to allow for horizontal resizing on those panes. I will attach a screenshot so you can see what I mean. Thanks.
![Screenshot from 2023-08-14 01-22-40](https://github.com/squidowl/halloy/assets/5975216/6e1c33c6-b333-4c3a-87cf-b6172ec82fe9)

**Comment by casperstorm** [comment]
I see the issue. Will look into fixing this!

**Comment by tstraus13** [comment]
So I can change the width of the left sidebar but what about the right? Would be great if you could resize with mouse because usernames and channel names could be vary in length. Thanks!
