### ISSUE TITLE
Bug Report: The windows executable doesn't pick up the configuration file in %appdata%\halloy.

### ISSUE THREAD

**Issue by KoxSosen** [squidowl/halloy#199]
When opening the halloy executable for the first time, the configuration "wizard" greats you with a message regarding setting up your configuration. However if you follow the instructions step-by-step, the `config.yaml` file in `%appdata%\halloy` won't be actually be read. 

At the moment, this issue can by solved by moving halloy to it's own directory, and adding a configuration file to the same directory, which halloy will successfully read.

**Comment by casperstorm** [comment]
<img width="400" src="https://github.com/squidowl/halloy/assets/2248455/73455dd0-07d2-4c34-9b1a-60e863e5624e">

I can't reproduce this. Maybe its a wording issue on our end?
When you see the above mentioned screen, you can get an option to `Open Directory` if you do that and create a `config.yaml` with your settings and then press `Refresh` it loads that config file.

**Comment by KoxSosen** [comment]
Thank you for testing, and apologies for the late response. Previously, with the steps you mentioned it didn't work, however now it does. Now, I'm able to create the `config.yaml` file in `%appdata`, and move the executable anywhere. Sorry for the hick up, closing this PR.
