### ISSUE TITLE
Disable IPv6 please

### ISSUE THREAD

**Issue by johndo100** [squidowl/halloy#200]
Hi,
I've just install Halloy. It is good looking and fast.
But my IPv6 address is on blacklist and be banned.
How can I config Halloy to use my IPv4 only which is not be banned.
I don't know how was my IPv6 be banned from 2017-2019 anyway. It is dynamic IP provide from my ISP.
Please help,
Thanks!

**Comment by casperstorm** [comment]
This seems like something the IRC client shouldn't manage.
