### ISSUE TITLE
Deskto notifications?

### ISSUE THREAD

**Issue by leaf-node** [squidowl/halloy#203]
Hi, thanks for the great IRC client.

I was wondering if you were interested in adding support for desktop notifications? On Linux, there's the `libnotify` system, and a simple binary named `notify-send`. This would help with getting a message while working with another application, a common user behavior.

Thanks! :smile:

**Comment by casperstorm** [comment]
Not that far from being merged - I just have been a little busy with IRL but will get it done ASAP.
