### ISSUE TITLE
Font settings ignored on Linux

### ISSUE THREAD

**Issue by adrian5** [squidowl/halloy#205]
It seems Halloy cannot find fonts on my system. The font being used is presumably some default/fallback and I get no error message.  I'm not sure if you had a chance to [test](https://github.com/squidowl/halloy/pull/58#pullrequestreview-1500873680) that yet.

I would imagine the libraries you're using are capable of detecting fonts on my system.

**Comment by andymandias** [comment]
I had this same issue and in my case at least (Fedora aarch64) it seems the issue is related to Flatpak.  When building from source I'm able to load fonts.

**Comment by adrian5** [comment]
Thanks for the feedback Andrew. In my case it was the binary release here from GitHub.

I'm now back on Hexchat which was my go-to client in the past. Until recently, I had accessed the major IRC networks via Matrix client, but the Matrix←→IRC bridges were removed, at least for LiberaChat.

**Comment by casperstorm** [comment]
@tarkah did you see this issue as well?

**Comment by casperstorm** [comment]
@adrian5 mind testing master branch? We just updated to master branch of iced which had a bunch of changes.
Including a few changes to font loading.

**Comment by adrian5** [comment]
@casperstorm Just tried a master (debug) build and fonts look normal now, as well as responding to `config.yaml` changes.

One exception is my NerdFont, which is accepted (being listed in the startup log) but doesn't seem to be used in the window. I can't tell which font I'm looking at instead, but the glyphs are different. I don't know if you want to investigate this further. Otherwise the core of this issue can be considered resolved I reckon.

**Comment by qauff** [comment]
I'm seeing this issue with the snap installed version. Can confirm that fonts are loading properly when running `cargo run --release` on the latest main branch.
