### ISSUE TITLE
thread 'main' panicked at 'Error in Surface::get_current_texture_view: Validation Error

### ISSUE THREAD

**Issue by wiiznokes** [squidowl/halloy#208]
I know it probably not the fault of this app, maybe iced or wgpu. The app crashed at some point, maybe when my computer went to sleep.

```
thread 'main' panicked at 'Error in Surface::get_current_texture_view: Validation Error


Caused by:
    Parent device is lost
', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.1/src/backend/direct.rs:778:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
^C
[1]+  Termine 101             halloy
```

I'm on Linux, Ubuntu 23.10

**Comment by casperstorm** [comment]
Do you still have issue with current release?
Do you have issue with building from source?
And if not too much trouble, do you have trouble running `tour` example of [iced](https://github.com/iced-rs/iced)?

**Comment by wiiznokes** [comment]
I don't remember, i think we can close this
