### ISSUE TITLE
Your own private messages are skipped on bouncer backlogs

### ISSUE THREAD

**Issue by rniii** [squidowl/halloy#213]
For context, I have soju set up

Upon reconnecting, I receive all the backlogs just fine, but my own private messages are missing
On channels I still receive my own messages, and it does seem to be a halloy issue (Revolution receives them just fine), I'm guessing they're ignored for some reason?

**Comment by rniii** [comment]
If you send a message on another client, you see it on channels, but not PRIVMSGs. That might be easier to test with

**Comment by casperstorm** [comment]
Finally got to fix this issue @rniii in #268.
