### ISSUE TITLE
Cant login with special character as first letter in password.

### ISSUE THREAD

**Issue by ramsesatabusimbel** [squidowl/halloy#219]
I cant logon to znc with a password starting with *. It errors out with "expected letter or number" when i try to connect.

**Comment by casperstorm** [comment]
@ramsesatabusimbel do you enter it sourrunded by `"`?
```yaml
password: "*foobar_password"
```

**Comment by ramsesatabusimbel** [comment]
> @ramsesatabusimbel do you enter it sourrunded by `"`?
> 
> ```yaml
> password: "*foobar_password"
> ```

I will try that, wiki says nothing about " sign with password entry.

**Comment by ramsesatabusimbel** [comment]
It worked fine logging on, but no channels where joined of 4?

**Comment by casperstorm** [comment]
That sounds like a bouncer issue 🤔 
I've used znc without any issues on halloy.

I will close this comment since the original question has been solved. Feel free to add a new issue if you find anything else.
Also feel free to join our irc channel to chat about it.
