### ISSUE TITLE
Many Server Connection Reports

### ISSUE THREAD

**Issue by andymandias** [squidowl/halloy#226]
Sometimes when waking my laptop from sleep I get many `connection to server lost` and `connection to server restored` messages in a row all with the same timestamp (example screenshot attached).  I'm unable to reliably reproduce the behavior, and I currently don't have any reason to believe that they're false reports, but they do take up a big block in the backlog.  I don't believe we want to suppress that information entirely, but I think it would be nice if the messages could be condensed into a single pair of `connection to server lost` and `connection to server restored` messages.
   
![Screenshot from 2024-02-05 14-27-45](https://github.com/squidowl/halloy/assets/5768180/2d67b4fb-e312-4ca8-9efd-6128bc79432d)

**Comment by andymandias** [comment]
Looking into this a bit more, these (dis)connections are all happening within a tenth of a second.  It seems like these shouldn't happen since I haven't changed the reconnect delay from the default 10s.  I've written a simple message filter to coalesce the messages into single a disconnect/connect pair, but maybe it'd be better to stop them at the source?

**Comment by casperstorm** [comment]
I wonder if @tarkah has any thoughts about this.

**Comment by tarkah** [comment]
Make sure to set reconnect delay https://github.com/squidowl/halloy/blob/main/data%2Fsrc%2Fconfig%2Fserver.rs#L39-L41 in your server config

**Comment by tarkah** [comment]
Relevant code is here, we always try to delay before reconnecting. All branches which disconnect set last retry to now. So either reconnect delay is somehow zero or something is weird with Instant and sleep.

https://github.com/squidowl/halloy/blob/main/data%2Fsrc%2Fstream.rs#L85-L92

**Comment by andymandias** [comment]
Thank you for your thoughts and the code reference.  I've added some diagnostic prints around reconnection to the debug log and will report back with details the next time it occurs.

**Comment by andymandias** [comment]
The delay is happening between `data/src/stream.rs` and `src/main.rs` (as expected, but best to confirm in my experience).  I don't know why the wait time between send and receive is sometimes very long (~1.5 hours the most recent time this issue occurred), but I expect it's out of the scope of Halloy.  I've drafted a PR which I believe will give users accurate reconnect/disconnect times;  just waiting for the issue to occur again to test abnormal behavior (normal behavior appears to be effectively unchanged, as desired).  I think we can close this issue with PR #270 (or something like it).

**Comment by andymandias** [comment]
Correct, it only manifests when resuming from sleep.  More specifically when sleeping my laptop, taking it to a new location (with a different wifi network), then waking it at the new location.  (And unfortunately does not reproduce consistently.)  I believe it's only occurring when I don't visit the workspace Halloy is in after waking from sleep, but that's still speculative.

**Comment by tarkah** [comment]
The only way there would be a delay in the main UI thread / iced loop receiving these messages is if the winit event loop is "paused". But the async task / stream subscription isn't tied to the winit event loop so it's still running and sending these messages to be processed but until winit starts running again, they just sit in a channel waiting.

This is a super theory but kind of lines up with your report.

**Comment by andymandias** [comment]
Closing this since #270 has been merged, as I suspect the disconnection/reconnection cycles are not a Halloy issue.  Will open another issue if I find out otherwise.
