### ISSUE TITLE
No text input box visible - OSX sonoma 14.2.1 Macbook Air M2

### ISSUE THREAD

**Issue by mynameisjonas** [squidowl/halloy#227]
I'm running the latest build compiled from source but do not have any text input box visible or selectable. I see from other screenshots there should be a text input box at the bottom of each pane with"Send message" but I simply do not have that in any theme. 

I have` input_visibility: Always ` in the config.yaml

<img width="973" alt="image" src="https://github.com/squidowl/halloy/assets/4792161/c258a1b0-92e1-45af-8fd5-b65c5511c7c1">

**Comment by casperstorm** [comment]
I am sitting on a M1 Pro, 14.3.1 and has no trouble seeing the input bar 🤔 

<img width="576" alt="Screenshot 2024-02-10 at 20 57 16" src="https://github.com/squidowl/halloy/assets/2248455/9622d1f3-68c2-47bb-9e6c-f5eaf873571d">

**Comment by tarkah** [comment]
I have an M2 MBA I can test on later

**Comment by tarkah** [comment]
I have an M2 MBA I can test on later
