### ISSUE TITLE
Setting zoom / font size?

### ISSUE THREAD

**Issue by sainttttt** [squidowl/halloy#233]
I was wondering if there's a way to set the font size or the application zoom setting somehow? I'd love to give it a go but it's way too small on my screen. Thanks!

**Comment by tarkah** [comment]
The GUI framework we use allows us to have a global scale factor. We just need to enable it via configuration.

For font size, you can set that in the config, https://github.com/squidowl/halloy/blob/9bc18caf932a710ad4d1b088ed64d968d915f9fe/config.yaml#L43

**Comment by tarkah** [comment]
Yup, scale factor will preserve layout so you won't have any cutoff. It's an easy add, I'll try to get around to it this upcoming week!

**Comment by casperstorm** [comment]
PR here: https://github.com/squidowl/halloy/pull/234.

**Comment by casperstorm** [comment]
@sainttttt I've merged the feature to main, feel free to build a version from that :)
