### ISSUE TITLE
Feature Request: Topic Banner

### ISSUE THREAD

**Issue by andymandias** [squidowl/halloy#236]
On quiet channels, or when closing/opening Halloy repeatedly for whatever reason, the channel history can build up a backlog of `RPL_TOPIC` and `RPL_TOPICWHOTIME` messages (often the same ones over and over) that swamp out the more infrequent messages that are left.  I'd like to add the option to move those messages to a banner at the top of a channel pane, showing only the latest topic (along with who it was set by and when).

I've created a possible implementation [andymandias/halloy/topic-banner](https://github.com/andymandias/halloy/tree/topic-banner).
![Screenshot from 2024-02-24 15-44-39](https://github.com/squidowl/halloy/assets/5768180/0791e664-fe9b-43e0-be2b-3817fc6e457c)

**Comment by casperstorm** [comment]
I think that is a good idea, feel free to open a PR and we can work together on the design on it.

**Comment by casperstorm** [comment]
Thanks for implementing this, @andymandias! 🚀 
Done in #237.
