### ISSUE TITLE
Rendering Issues When Using Custom Font Family

### ISSUE THREAD

**Issue by andymandias** [squidowl/halloy#238]
When setting a font family in `config.yaml` I encounter two issues.

First, the bottom entry in context menus does not render any text:

![Screenshot from 2024-02-28 01-19-41](https://github.com/squidowl/halloy/assets/5768180/06368c25-9c61-456a-81c8-11cac27a4849)
![Screenshot from 2024-02-28 01-19-49](https://github.com/squidowl/halloy/assets/5768180/6dd03d47-b98e-4bd4-967a-9f845a92218f)

I tried swapping the order of the items in the context menu to see if the issue pertained to a particular menu item, but its always the last item in the context menu that does not render text.  (The screenshots didn't capture my cursor for some reason, but in both screenshots I am selecting the last item in the context menu.)

Second, the ← arrow in the text that shows when no buffer is selected does not render properly.

![Screenshot from 2024-02-28 01-19-55](https://github.com/squidowl/halloy/assets/5768180/25f1c26f-29f7-4d6e-8e10-8b12de3abfe9)

Neither of these issues occurs when I do not set a custom font family.

I'm running Halloy under Fedora Asahi Remix 39.  This occurs with every font I've tested so far, one of which is [Fira Code](https://fonts.google.com/specimen/Fira+Code).

**Comment by casperstorm** [comment]
I've noticed this as well, and have begun debugging it. It was caused by the new version of Iced.

**Comment by andymandias** [comment]
The context menu no longer shows text on Linux when customizing the text size.  For anyone else running into this, using the default text size is a workaround.
![Screenshot from 2024-03-06 01-26-39](https://github.com/squidowl/halloy/assets/5768180/904e62e2-56dc-4b60-b984-9956ffc1bc28)
