### ISSUE TITLE
CertFP error on macOS when connecting to server

### ISSUE THREAD

**Issue by davlgd** [squidowl/halloy#280]
I followed the [LiberaChat guide](https://libera.chat/guides/certfp) to generate a PEM certificate:

```
openssl req -x509 -new -newkey ed25519 -sha256 -days 1096 -nodes -out libera.pem -keyout libera.pem
```

But when I connect to the server with SASL/External, I get this message:

```
connection to server failed (a TLS error occured: Unknown format in import.)
```

I'm under macOS 14.4 (Darwin 23.4.0 arm64), with OpenSSL 3.2.1 (installed via `brew`)

**Comment by tarkah** [comment]
On macos, you need to split the public and private keys to separate files. In halloy, you can then import each via the external.cert and external.key fields separately.

**Comment by davlgd** [comment]
So I created the cert/key with: 

```
openssl req -x509 -new -newkey ed25519 -sha256 -days 1096 -nodes -out libera.pem -keyout libera.key
```

The SASL parameters in my config files are:

```
sasl: 
      !external
        cert: "/some/path/libera.pem"
        key: "/some/path/libera.key"
```

But I still have the same error: 

```
connection to server failed (a TLS error occured: Unknown format in import.)
```

Am I still doing something wrong ?

**Comment by casperstorm** [comment]
Can you try `!External` with capital?

**Comment by davlgd** [comment]
<img width="705" alt="image" src="https://github.com/squidowl/halloy/assets/1110600/b582e80c-6d8b-49b1-b850-3725d5f6d291">

**Comment by casperstorm** [comment]
Ah sorry, didn't see you actually got a response from the server. It is indeed `external` then as it suggest. :)

**Comment by casperstorm** [comment]
@davlgd I just want to let you know that we are currently trying to figure out this macOS issue.
We will get back to you ASAP.

**Comment by oldgalileo** [comment]
@casperstorm was there an update to this?

**Comment by casperstorm** [comment]
> @casperstorm was there an update to this?

Not yet, the thing is that it works on Linux, which @tarkah has confirmed so we think it comes down to the way we generate it on macOS - I haven't yet had time to sit down and play with it but at this moment I don't think it's a bug in Halloy 🤔

**Comment by tarkah** [comment]
This isn't a bug for Halloy. Trying to inspect the certificates on macos with the `security verify-cert` command returns the same error.

So it must be how certs are generated on macos and maybe we can't use openssl and need to use the built-in keychain or something?

**Comment by oldgalileo** [comment]
I'm not sure this makes sense. To quickly sanity check that, I generated an ed25519 certificate on my Linux box and then copied it to my machine to no success.

I think maybe it could be to do instead with macOS's `SecureTransport` for SSL? I'm going to quickly test with a `tokio-rustls` version which uses I think `ring` or `aws-lc` under the hood instead of `openssl` or the system `SecureTransport` lib.

**Comment by tarkah** [comment]
Thanks @oldgalileo! Based on your assessment you seem to be much more familiar with this than me so your help is much appreciated!

**Comment by tarkah** [comment]
And I'm very open to moving to rustls if we confirm it "just works" on all three platforms

**Comment by tarkah** [comment]
@davlgd the fix for this has been merged and will be available on the next release (soon!)
