### ISSUE TITLE
Number in text input when switch back workspace in i3 window manager

### ISSUE THREAD

**Issue by auronandace** [squidowl/halloy#284]
When changing workspaces in the i3 window manager the number of the workspace will be entered into the text input box when you switch to the workspace with halloy selected in it.

For example, if I was on workspace 1 and halloy was on workspace 2 and I switch to workspace 2 (pressing mod(super)+2) then the number 2 will be in the text input box.

Switching away from the workspace doesn't have the same effect, only switching back to it does.

**Comment by auronandace** [comment]
The mod key I use in i3 is the super key (with the windows logo on it) rather than alt. Does that mean someone needs to add that to upstream along with the already added alt check?

**Comment by ltning** [comment]
I see this on FreeBSD with Windowmaker too. 'Alt'+'number'. So it's not just Linux :)
