### ISSUE TITLE
Feature Request: Option to Indicate Absent Users in Channel

### ISSUE THREAD

**Issue by andymandias** [squidowl/halloy#287]
I think it would be nice if there was an option to change their nickname appearance of absent users in the the channel history, such as

![Screenshot from 2024-03-19 21-26-26](https://github.com/squidowl/halloy/assets/5768180/e24abaea-5be4-4609-8516-4d6642c70222)

where nicknames for users that are not present appear as `theme.colors().info.low_alpha` (not particular to the color, just wanted it to be distinguished from the away state coloring while mimicking away's transparent cue).  The aim of this feature, from my perspective, is to give an option to further suppress server messages by providing another mechanism to quickly see whether a user is currently present.

**Comment by casperstorm** [comment]
What is the difference between absent users and away users?

**Comment by andymandias** [comment]
My (maybe incorrect understanding) was that away users are still in the channel but have away set (the IRC command/status), while what I'm calling absent users would be ones that are no longer in the channel.  My assumption is that users that are still in the channel but away could be waiting for a reply, while users that are no longer on the channel probably won't see a reply.  Seeing that status right next to the message (rather than searching through the nick list) would be handy in my use, but I'm not sure if it's has wide enough appeal.

**Comment by andymandias** [comment]
To avoid messing with the historical accuracy of the chat logs, how about this instead: a hover state for usernames which shows a small pane with the user's current status (present, away, absent, and access levels)?

**Comment by andymandias** [comment]
Got delayed by pondering the Rust heap, but I had some time to put together a mock up of the tooltip version of this feature.  Pictured are absent/present state tooltips.  There is also an away state that looks similar to the present state, just with an info colored dot (and it says Away instead of Present);  couldn't find a user to test with before my dev time is up.

![absent_tooltip](https://github.com/squidowl/halloy/assets/5768180/debd6e9d-99fb-4f9a-b401-12d731ffc141)
![present_tooltip](https://github.com/squidowl/halloy/assets/5768180/73796a29-8f45-44d1-b604-24df268b8a44)

**Comment by casperstorm** [comment]
> absent users would be ones that are no longer in the channel

I am still a bit unsure about this. I feel like irc users operates on two states; away and not-away.
However, a tooltip hovering users (in nicklist) is a fantastic idea with useful information about them.

**Comment by andymandias** [comment]
Consolidating "user with away status" and "user no longer in the channel" into one tooltip status could work for me.  I'm mostly interested in a quick way to determine whether someone who sent a message is still around to see a response.  I would expect someone who left the channel to be less likely to see a message than someone who set away, but both could be indicative of someone who probably wouldn't see a response.  I can always scroll through the nicklist to see if a user is in it (and whether they're away), but in channels with 1000+ users it can take a bit to manually find (or not) a user in the nicklist.

**Comment by andymandias** [comment]
Another mockup, with some access levels added and hopefully clearer status names.

![in_channel](https://github.com/squidowl/halloy/assets/5768180/2cc282ac-ce0d-4e02-923c-a4daa0af9aab)
![away](https://github.com/squidowl/halloy/assets/5768180/3fdf1b6f-f244-4388-8839-c5923aa83377)
![not_in_channel](https://github.com/squidowl/halloy/assets/5768180/c59dc27e-b9aa-4001-abec-95c6f5d995b2)

**Comment by andymandias** [comment]
Sounds good to me!  I can clean up the mockup and open a PR if you're convinced it's worth going forward with.

**Comment by casperstorm** [comment]
> Sounds good to me! I can clean up the mockup and open a PR if you're convinced it's worth going forward with.

100%, i just had to understand it and i think it make sense and id like to see it in Halloy!
Happy you wanna give it a stab.
