### ISSUE TITLE
version 2024.4 still comes with the config.yaml file 

### ISSUE THREAD

**Issue by YouFoundAlpha** [squidowl/halloy#289]
Version 2024.4 still comes with the config.yaml file instead of the config.toml file
Can this be changed for the flatpak version because I got confused when my config file looked completely different from how the [docs](https://halloy.squidowl.org/configuration/index.htmll) version looks like
The same issue is also in the .appImage from the [Releases page](https://github.com/squidowl/halloy/releases/tag/2024.4)
I have tried both

**Comment by YouFoundAlpha** [comment]
I can put a YAML to TOML file converter in js into the [migrating-from-yaml.html](https://github.com/squidowl/halloy/blob/gh-pages/guides/migrating-from-yaml.html) 
If you would like that

**Comment by casperstorm** [comment]
Currently only when you build from source you get TOML version.
To view YAML docs, please look here: https://github.com/squidowl/halloy/wiki

We are currently wrapping up the release, and then we will submit. Sorry for the confusion.

**Comment by casperstorm** [comment]
Releasing 2024.5 now with TOML support.
Should be here in a few minutes: https://github.com/squidowl/halloy/releases
