### ISSUE TITLE
[improvement] macOS Big Sur+ app icon

### ISSUE THREAD

**Issue by vtu-dog** [squidowl/halloy#298]
Ever since Big Sur rolled around, macOS uses a [new app icon template](https://developer.apple.com/news/?id=swmsf9kt) - a square with rounded corners. My personal preference is to always use this style to ensure consistency across the entire system.

I created an icon you could use by cropping the README banner using `Image2Icon` (.icns zip [here](https://github.com/squidowl/halloy/files/14747313/Halloy.icns.zip), .png preview below) - default settings, `Big Sur App` preset. For now I can set it manually by invoking `fileicon set APP_PATH ICNS_PATH`.
<img width="368" alt="Halloy" src="https://github.com/squidowl/halloy/assets/32556544/a309d80a-328b-4c83-9a58-e56ebd448bc1">

**Comment by casperstorm** [comment]
We have a discussion going here to address the icon!

https://github.com/squidowl/halloy/discussions/286

**Comment by casperstorm** [comment]
I've re-done the icon, and opened a PR (#299).

<img width="687" alt="Screenshot 2024-03-26 at 16 45 28" src="https://github.com/squidowl/halloy/assets/2248455/ec0f2ec6-938d-4d72-8455-7c1fdeaee2b6">
