### ISSUE TITLE
[Improvements] Proxy support ?

### ISSUE THREAD

**Issue by SyntheticBird45** [squidowl/halloy#301]
I need proxy support. A socks field in the [servers] toml config would be great

**Comment by ramajd** [comment]
I can take care of this feature, if no one already started that.

**Comment by casperstorm** [comment]
> I can take care of this feature, if no one already started that. 

Feel free to to grab this!

**Comment by casperstorm** [comment]
@ramajd: Feel free to publish a draft PR early, if you want to discuss or get feedback. We are happy to help you get to the finish line!

**Comment by ramajd** [comment]
@casperstorm  just submitted the #350 . the initial implementation might not be efficient enough. it would be great if I had any feedback about this implementation

**Comment by casperstorm** [comment]
This has been merged to main, and issue should be fixed.
Please test main, and see if it functions as expected.
