### ISSUE TITLE
Seems like the client is encoding the symbols for colors.

### ISSUE THREAD

**Issue by Iliannnn** [squidowl/halloy#319]
How can I get Halloy to display them properly?
![image](https://github.com/squidowl/halloy/assets/72648901/3bbef2f2-f10d-4e26-a3a2-33b7dfec6bf5)

**Comment by casperstorm** [comment]
This is due to [irc formatting characters](https://modern.ircdocs.horse/formatting#characters). We really need rich text from upstream before we can do anything about it.

**Comment by casperstorm** [comment]
This has been fixed, and will be available in next release.
