### ISSUE TITLE
Save directory in Windows does not work

### ISSUE THREAD

**Issue by TwinTusks** [squidowl/halloy#330]
Per title, the config 

```
save_directory = "C:\Users\arthur\Desktop"
```

Generates an error, see below image, while if I replace _C:\Users\arthur\Desktop_ with _$HOME/Downloads_ works.

![Halloy Error](https://github.com/squidowl/halloy/assets/93845559/82ee2f67-1f2d-45d8-98b6-112886ecfc08)

**Comment by tarkah** [comment]
Try this:

`C:\\Users\\arthur\\Desktop`

**Comment by TwinTusks** [comment]
> Try this, you need to escape the slashes:
> 
> `C:\\Users\\arthur\\Desktop`

This does clear the error, however, I might be mistaken, DCC still askes me to accept the download (and location), isnt this option serves as auto accept?

**Comment by casperstorm** [comment]
> > Try this, you need to escape the slashes:
> 
> > 
> 
> > `C:\\Users\\arthur\\Desktop`
> 
> 
> 
> This does clear the error, however, I might be mistaken, DCC still askes me to accept the download (and location), isnt this option serves as auto accept?

No, it's not auto accept. It simply sets the default path to where it will ask you to save the file.
