### ISSUE TITLE
sha256sums on release

### ISSUE THREAD

**Issue by KaiKorla** [squidowl/halloy#334]
Please create a sha256sum.txt or something similar with the sha256sums of each file in a release.

**Comment by YouFoundAlpha** [comment]
I'm currently finding a solution to this using Github actions
I'll make a pull request as soon as I have tested the solution

**Comment by casperstorm** [comment]
Sorry for late response on this, but it is now added to releases.

**Comment by YouFoundAlpha** [comment]
> Sorry for late response on this, but it is now added to releases.
> Thanks for the help work, @YouFoundAlpha.

The usual names for the SHA256 hashes files are SHA256SUM or SHA256SUMS or checksums.txt
Could you maybe change it @casperstorm ?
