### ISSUE TITLE
add extra keybinds

### ISSUE THREAD

**Issue by vidje** [squidowl/halloy#373]
I would like to see and option to customize keybinds for the following actions:
"Leave channel"
"Close query"
"Toggle sidebar"

and in general, it would be nice that any action that you can do by clicking the mouse or going through the command menu is available as a keybind as well

**Comment by casperstorm** [comment]
This has been merged: https://github.com/squidowl/halloy/commit/100fef3a7709b12027317b6908ae68ee844388bb.
