### ISSUE TITLE
Embed one or more scripting languages

### ISSUE THREAD

**Issue by Mardeg** [squidowl/halloy#38]
Or not, but they are fun to play with. I have no preference which but I'll list some here with their licenses and welcome further suggestions.

Uniquely rusty languages (MIT OR Apache-2.0 licensed):
* Dyon - https://crates.io/crates/dyon 
* Rune - https://crates.io/crates/rune
* Duckscript - https://crates.io/crates/duckscript

More familiar languages:
* Lua - https://crates.io/crates/mlua (MIT)
* Tcl - https://crates.io/crates/molt (BSD-3-Clause)
* Lisp - https://crates.io/crates/spaik (BSD-2-Clause) or https://crates.io/crates/ketos (MIT OR Apache-2.0)
* Scheme - https://crates.io/crates/passerine (MIT) or https://crates.io/crates/guile (GPL-3.0)
* Python(esque) - https://crates.io/crates/starlark (Apache-2.0)
* Javascript - https://crates.io/crates/deno (MIT)

**Comment by LordPraslea** [comment]
Hi, this was closed and marked as completed, which scripting language is embedded? 
I'd second on embedding one scripting language as it allows for extendability without affecting the core. TCL is commonly used for almost 30 years in IRC. But I'm open to Luaa or javascript as both can be embedded :)
