### ISSUE TITLE
Add Matrix support

### ISSUE THREAD

**Issue by superlou** [squidowl/halloy#388]
Could Halloy support connecting to Matrix servers, even if only for IRC-like text chatting? This would cut down on the number of apps I have open and remembering which chat rooms I have on which protocol.

I completely understand if this is a won't-fix, since it's definitely outside the scope of a traditional IRC client.

**Comment by casperstorm** [comment]
That is out of scope for this project!

**Comment by Mikaela** [comment]
https://github.com/progval/matrix2051 might interest you
