### ISSUE TITLE
Using excessive bandwidth with X11 forwarding.

### ISSUE THREAD

**Issue by RealKindOne** [squidowl/halloy#394]
I'm using commit bf876c2dcd7c242d8abbab501b61ffddd45917dd.

1. Compile on *nix machine.
2. Setup *nix to allow X11 forwarding (ssh -X).
3. ssh -X into *nix machine from Windows. (I use MobaXterm).
4. Open network monitoring program on Windows (I use old version of NetWorx) (or nload on *nix machine).
5. Launch halloy from ssh'd session.
6. hallow is using 100 - 200 Kbytes per second. This should be around 1 - 2 Kbytes per second.
7. See picture below.
![halloy](https://github.com/squidowl/halloy/assets/20209685/4cffa140-b350-41b6-a066-77d6f2b8ad61)

I'm guessing halloy is re-drawing the entire screen when nothing is happening?

**Comment by tarkah** [comment]
We use the `iced` framework which is based on the elm architecture. A `view` is returned only after `update` is called, which effectively means only after _state_ changes. `iced` currently doesn't diff `view` during render, so an identical `view` (maybe state didn't actually change during `update`) will cause a redraw.

We have a "tick" subscription to drive certain behavior which fires every 1 second. This calls `update`, meaning even if no IRC messages come in and you do not interact with the app, it'll still `update` every 1 second which then triggers `view` then a redraw. 

There's also certain IRC messages you will receive that update state, but maybe not in a way that changes the UI (messages on closed channels, such as JOINs / PARTs, etc). But again, this will still cause `view` -> rerender.

Until `iced` offers `view` diff'ing, there's nothing we can do here to prevent this.
