### ISSUE TITLE
Delete text does not work as intended

### ISSUE THREAD

**Issue by krstp** [squidowl/halloy#398]
The text removal via `Backspace/Delete` does not work as intended. Whenever I type something, for example `abcdef` and try to delete all characters at speed (no slow `delete` pushing, but rather hold the `delete/backspace` button), the UI jumps a letter or two in this case. Such as after the cursor makes it to the beginning at `0` position, supposedly deleting all characters, two characters such as `bc` are leftout at the front of the coursor, with cursor reverted to its initial position at `0`.  

I am pretty sure this relates to slow typing issue at:
https://github.com/squidowl/halloy/issues/397

Reference:
System: `Linux; 6.8.0-35-generic; Ubuntu; x86_64`

**Comment by casperstorm** [comment]
I believe this is fixed in main. Will be available in next release.
Feel free to re-open if not.
