### ISSUE TITLE
Feature Request: Clickable URLs

### ISSUE THREAD

**Issue by condean** [squidowl/halloy#399]
It would be nice if URLs were detected within chats and clickable or at least right-clickable or shift/alt clickable to open in browser. 

I'm on macOS Monterey if that makes a difference.

Loving Halloy! Thanks for an awesome client!

**Comment by casperstorm** [comment]
Duplicate of https://github.com/squidowl/halloy/issues/75.
Trust me, we are implementing this feature as soon as the GUI framework we use gives us the opportunity!
