### ISSUE TITLE
Multi-window support

### ISSUE THREAD

**Issue by condean** [squidowl/halloy#400]
Unless I am missing something I'm only able to have one halloy window instance available for use.  It would be great to be able to have multiple windows open so I can have separate windows dedicated to specific servers or channels. 

Some additional features that would be nice to go along with this but aren't totally necessary:

- An option to open a specific buffer in a new window either through a command and/or a right click menu item.
- An option to predefine buffer layouts for separate windows in the config file and assign them to a command or assign them to specific servers/channels.

I'm on macOS Monterey if that makes a difference.

I'm absolutely loving halloy! Thanks for an awesome client!

**Comment by casperstorm** [comment]
Multi-window is supported by the GUI framework we use, so this is possible to implement. Thanks for the suggestion.
