### ISSUE TITLE
Channels not shown when server is connected to

### ISSUE THREAD

**Issue by hahuang65** [squidowl/halloy#402]
I've got a soju bouncer connection configured. This was working really well 2 days ago.

However, today I get to my computer, and the buffer list is empty. I see the server, and the logs say that the server is connected, but it doesn't look like it's adding the channels to the channel list.

I've tried leaving the server and restarting the application but nothing seems to be working. What can I attach to help debug this?

**Comment by casperstorm** [comment]
That sounds strange. Could you provide the halloy log file?

We are quite a few using soju and haven't heard about this issue before!

**Comment by andymandias** [comment]
This sounds like the state when `soju` itself has been disconnected from the network.  Why that would be the case, I don't know.  What response do you get to `/msg BouncerServ network status`?

**Comment by hahuang65** [comment]
> This sounds like the state when `soju` itself has been disconnected from the network. Why that would be the case, I don't know. What response do you get to `/msg BouncerServ network status`?

Bizarre. When doing that from halloy, I get no response.
With `senpai`, connected to the same bouncer, same account, it says I'm connected and attached to 43 channels.

I have noticed in Halloy that there seems to be constant disconnects and reconnects:

```
11:51  ∙ connection to server restored
11:53  ∙ connecting to server...
11:53  ∙ connected
11:54  ∙ connecting to server...
11:54  ∙ connected
11:56  ∙ connecting to server...
11:56  ∙ connected
11:59  ∙ connection to server lost (ping timeout)
11:59  ∙ connection to server restored
12:02  ∙ connection to server lost (ping timeout)
12:03  ∙ connection to server restored
12:06  ∙ connection to server lost (ping timeout)
12:06  ∙ connection to server restored
12:09  ∙ connection to server lost (ping timeout)
12:10  ∙ connection to server restored
12:13  ∙ connection to server lost (ping timeout)
12:13  ∙ connection to server restored
12:16  ∙ connection to server lost (ping timeout)
12:17  ∙ connection to server restored
12:20  ∙ connection to server lost (ping timeout)
12:20  ∙ connection to server restored
12:23  ∙ connection to server lost (ping timeout)
12:24  ∙ connection to server restored
12:27  ∙ connection to server lost (ping timeout)
12:27  ∙ connection to server restored
12:30  ∙ connection to server lost (ping timeout)
12:31  ∙ connection to server restored
12:34  ∙ connection to server lost (ping timeout)
12:34  ∙ connection to server restored
12:37  ∙ connection to server lost (ping timeout)
12:38  ∙ connection to server restored
12:41  ∙ connection to server lost (ping timeout)
12:41  ∙ connection to server restored
12:44  ∙ connection to server lost (ping timeout)
12:45  ∙ connection to server restored
12:48  ∙ connection to server lost (ping timeout)
12:48  ∙ connection to server restored
12:51  ∙ connection to server lost (ping timeout)
12:52  ∙ connection to server restored
12:55  ∙ connection to server lost (ping timeout)
12:55  ∙ connection to server restored
12:58  ∙ connection to server lost (ping timeout)
12:59  ∙ connection to server restored
```

Where do I find the logfile on macOS?

**Comment by casperstorm** [comment]
With Halloy open you can press cmd+k to bring up command bar. In there, there's a shortcut which opens config directory which has the log file.

For fun, could you try with a vpn or with a mobile tethering?

**Comment by hahuang65** [comment]
Here's the attached log. It connects, then times out... and reconnects. Twice.

Will try the VPN now.
[halloy.log](https://github.com/user-attachments/files/15918941/halloy.log)

**Comment by hahuang65** [comment]
Both VPN and Mobile Hotspot has the same behavior as my normal Wifi... unfortunately :(

**Comment by tarkah** [comment]
Can you please confirm which version of `soju` you're connecting to?

**Comment by hahuang65** [comment]
> which I'd increase: https://halloy.squidowl.org/configuration/servers.html

Do you have a recommendation for values?

Also, FWIW... `weechat`, `senpai` both don't have an issue connecting... and Halloy on my Arch Linux machine is also fine, with the same configuration as Halloy on this macOS where I'm having the issue from.

**Comment by tarkah** [comment]
Can you share your config?

**Comment by hahuang65** [comment]
> Can you please confirm which version of `soju` you're connecting to?

Not sure, it's whatever version https://man.sr.ht/chat.sr.ht/bouncer-usage.md is running.

**Comment by tarkah** [comment]
Hmm nothing seems out of place w/ the config. Can you please run with `RUST_LOG=trace halloy` and then upload your log? This will let us see the actual IRC messages and may be helpful to know where the server stopped responding.

**Comment by hahuang65** [comment]
[halloy.log](https://github.com/user-attachments/files/15920069/halloy.log)

Here's the trace log.

**Comment by tarkah** [comment]
Hmm it appears to die after we send `CAP END`. This leads me to believe you're passing in the wrong password via the password file, so it silently kills the connection when registration ends. 

Can you please confirm you password file doesn't contain any trailing newlines? `hexdump -c ./path/to/password/file`

**Comment by hahuang65** [comment]
> Can you please confirm your password file doesn't contain any trailing newlines?

```
$ hexdump -c ./.password
$
```

**Comment by hahuang65** [comment]
hahaha stupid stupid on my part. My `install.sh` script that sets up my halloy configuration overwrote my `.password` file. It was empty. So sorry for making you guys chase your tails.

**Comment by tarkah** [comment]
Lol no worries, glad it was an easy fix in the end! It's pretty lame the servers silently fail, I guess we can assume an auth error between CAP END and timeout before another message and display something more helpful in the client
