### ISSUE TITLE
[macOS] Build failure on most recent main

### ISSUE THREAD

**Issue by ColinMcKechney** [squidowl/halloy#403]
Looks like one of the recent commits caused a build failure on macOS (SHA: 05c40e97208e65af5676d557f2d29219821bb3dc). I've attached a screenshot of the errors: 
<img width="920" alt="image" src="https://github.com/squidowl/halloy/assets/61918683/f9a94065-6415-42d0-a3ce-beb4d7ccb373">

**Comment by casperstorm** [comment]
This is a regression after: https://github.com/squidowl/halloy/pull/401.
I've made https://github.com/squidowl/halloy/pull/404 which will fix it.
