### ISSUE TITLE
Changing the buffer background color

### ISSUE THREAD

**Issue by icyphox** [squidowl/halloy#416]
Hey there! I love Halloy and it works beautifully. I was wondering if it would be possible to somehow change the buffer background color? Here's my custom theme, and what it looks like. I'd like for the buffer background to match the rest of the app (so `#f4f4f4`) for better text clarity. Currently it seems to be computing a few shades darker than the configured `pallete.background`(?).

```toml
name = "icy"

[palette]
background = "#f4f4f4"
text = "#333333"
action = "#509c93"
accent = "#509c93"
alert = "#d69822"
error = "#db7070"
info = "#b870ce"
success = "#7c9f4b"
```

<img width="1777" alt="Screenshot 2024-07-16 at 9 03 25" src="https://github.com/user-attachments/assets/c0cbcd60-2fac-48b6-b442-d996bea6de39">

**Comment by casperstorm** [comment]
Correct, right now we do some calculations on some of the provided theme colors. This does indeed limit certain things.
Right now there's not a solution for you, but I am annoyed by it my self so i would like to re-visit colors very soon. Perhaps it's time for a bigger refactor to provide even more control.

**Comment by sink666** [comment]
I believe a way to summon a 'test buffer' that has examples of every colorable element would be useful as well.

**Comment by casperstorm** [comment]
> I believe a way to summon a 'test buffer' that has examples of every colorable element would be useful as well.

Great idea.

**Comment by rniii** [comment]
I would like to suggest the same for the transparent foreground colors (like the topic banner) because with how it simply reduces the alpha by a fixed value it can make the contrast unreadable. I think right now, if you'd want to avoid adding more colors it'd be nice if the alpha of these could be a setting instead, or at least disabled

**Comment by casperstorm** [comment]
> I would like to suggest the same for the transparent foreground colors (like the topic banner) because with how it simply reduces the alpha by a fixed value it can make the contrast unreadable. I think right now, if you'd want to avoid adding more colors it'd be nice if the alpha of these could be a setting instead, or at least disabled

It's in the works!
