### ISSUE TITLE
Support 0x03 color codes

### ISSUE THREAD

**Issue by nc7s** [squidowl/halloy#418]
As documented in https://modern.ircdocs.horse/formatting.html#color and seen in the wild (like OFTC), some clients send 0x03 delimited color codes. Currently, Halloy just prints them verbatim.

Example:

<blockquote>
04:03 BTS 03rust-gtk4-sys 100.8.2-2 uploaded to 12experimental by 11Matthias Geiger <werdahias@riseup.net> https://tracker.debian.org/rust-gtk4-sys
</blockquote>

(The U+FFFDs seem to be the result of GitHub filtering. They are actually 0x03.)

**Comment by casperstorm** [comment]
We are blocked by GUI framework. The GUI framework does not yet have rich text support.
It is being worked on, and once it merges we can start working on this (and #75)

**Comment by nc7s** [comment]
Wow, really fast. Thanks for the update!

**Comment by casperstorm** [comment]
@nc7s Its available if you build Halloy from main.
We will also release a new version here in a few days :)
