### ISSUE TITLE
Long AUTHENTICATE commands aren't split into chunks

### ISSUE THREAD

**Issue by glguy** [squidowl/halloy#427]
This only affects people with very long passwords, but with a max length nickname and password on libera.chat, for example, the message will need to be split into two chunks. Failure to do so will generate `:server 905 <nick> :SASL message too long`

Chunking behavior is described on https://ircv3.net/specs/extensions/sasl-3.1

This is a niche case, but it might be worth tracking for future implementation. In the meantime you can recover some extra space by not sending the authorization identity since you don't need to. The full message format is: `<authorization identity>\x00<authentication identity>\x00<password>` and SASL PLAIN specifies that when authorization identity is empty that it defaults to authentication identity. The only IRC client I'm even aware of that even lets you specify an authorization identity is mine - this is a niche feature.

**Comment by casperstorm** [comment]
Thanks for this, and the detailed explanation.
