### ISSUE TITLE
CTCP commands are case-insensitive

### ISSUE THREAD

**Issue by glguy** [squidowl/halloy#428]
CTCP commands are specified to be case insensitive. The current conditionals only check for capitalized versions. Most CTCP is unused by this can cause some *actions* to be missed in chat.

**Comment by andymandias** [comment]
<https://modern.ircdocs.horse/ctcp.html> doesn't say anything one way or the other, but it looks like <https://rawgit.com/DanielOaks/irc-rfcs/master/dist/draft-oakley-irc-ctcp-latest.html> does specify case insensitivity (contrary to older specifications).
