### ISSUE TITLE
Can't copy text out of buffers

### ISSUE THREAD

**Issue by glguy** [squidowl/halloy#435]
When I highlight text in the server window and press <kbd>⌘</kbd><kbd>C</kbd> I get some fragment of the line but not necessarily what I selected.

Tested on macOS

**Comment by tarkah** [comment]
Are you compiling yourself / running in dev profile / without optimizations? I've noticed it skips words in dev mode, but I've never seen an issue in release mode.

**Comment by glguy** [comment]
I ran the program with exactly `cargo run`

**Comment by tarkah** [comment]
Yeah it's just how slow things are without optimizations and certain runtime mouse events must get dropped. 

Closing as this is a non issue since things run fine with optimizations
