### ISSUE TITLE
How convenient is it to use Iced? What are some peculiarities?

### ISSUE THREAD

**Issue by Filipp-Druan** [squidowl/halloy#449]
Hello! Can you tell me how convenient it is to use Iced? Does the Model View Update architecture help you? How is the division of the program into several independent parts implemented?
I would be very grateful if you could share your thoughts on this issue.

**Comment by casperstorm** [comment]
You should join the Iced Discord server to discuss theses topics. You find that, among other information here: https://github.com/iced-rs/iced
Will close this issue, due to being out context for this project.
