### ISSUE TITLE
Feature request: Allow clicks on windows in sidebar to toggle restore/minimize

### ISSUE THREAD

**Issue by smakkerlak** [squidowl/halloy#451]
Tiny request: Clicking the button for a window that is currently shown and has focus should minimize the window. I'd like to be able to "toggle" the minimized state easily, to help look through channels that i normally keep out of the way.

**Comment by neutralparadoxdev** [comment]
I presume when you say 'window', you mean the pane containing the buffer for server, channel, etc.

I am working on a feature to have the sidebar buttons toggle the panes. It will be a configuration option and pressing the button will open and close the pane. The key thing is that it properly closes the pane. Which means pressing again will open in the next position where a pane would normally be opened. It wont open to its original position.

I can add a feature where pressing the button will only toggle if the pane is focused and closes it. Opening it again will not put it in its original position.

Would this be a suitable implementation for this feature?

**Comment by smakkerlak** [comment]
> I presume when you say 'window', you mean the pane containing the buffer for server, channel, etc.

Yup. General functionality for any pane that has a sidebar button/tab.

Your description seems fine - i can't think of a good way to make panes appear in an expected way consistently, outside of small optimizations like restoring the previous layout if a pane was added and removed without other changes.

**Comment by andymandias** [comment]
Should be completed with #514. Thanks for the suggestion and the help with implementation.
