### ISSUE TITLE
Update URL regex to include "," as valid URL

### ISSUE THREAD

**Issue by casperstorm** [squidowl/halloy#461]
When pasting a URL with a `,` - eg: https://www.google.com/maps/@61.0873595,-27.322408,3z?entry=ttu
Halloy fails to recognize the entire string as URL. See below.

Regex code to update is her: https://github.com/squidowl/halloy/blob/f613d2a596ab39d5cc9975cd71370694eebdffca/data/src/message.rs#L21

![image](https://github.com/user-attachments/assets/2e4fe9f1-2719-4488-8ae4-babffad16045)

**Comment by glguy** [comment]
More than `,` is missing if someone wants to add all the stuff in *extra*
