### ISSUE TITLE
Halloy logo attribution

### ISSUE THREAD

**Issue by Venefilyn** [squidowl/halloy#464]
Hi all!

Just stumbled upon this after looking through `iced`. I'm curious about the logo that is displayed and where it's from. In the screenshot and gif I can see a similar background style to the logo, but I can't figure out who made the bird logo

Could we get add the attribution and copyright for the logo somewhere in the repo? To me it would make sense in the README and on the website

To me there are many questions in my mind as I can't find any attribution. Was it made specifically for halloy? Who is the creator? Given that there is no attribution, is it AI? Is it from a contributor who works on halloy or a hired artist?

**Comment by casperstorm** [comment]
Hey,

Thanks, I take this post as a compliment. The logo idea was mine, and I had Midjourney help me create it. After creation, I had my friend @rasmusnielsen (https://www.rasmusnielsen.dk/) do the final edits, as he is a great icon designer.

The background story is that "Halloy" comes from "Halløj" ([ˈhaˈlʌj]), a Danish way to say "hey." Back in the 90s, there was a commercial with two seagulls who said "halløj" to each other. For some reason, that became my inspiration.

**Comment by Venefilyn** [comment]
Gotcha, thanks for the response!

> The background story is that "Halloy" comes from "Halløj" ([ˈhaˈlʌj]), a Danish way to say "hey." Back in the 90s, there was a commercial with two seagulls who said "halløj" to each other. For some reason, that became my inspiration.

Love the name, it's unique and stands out. It's friendly too!

> The logo idea was mine, and I had Midjourney help me create it.

To me that's a bit disappointing, and sort of why I wanted to create this issue to see what it is. I'm very much in the camp of AI being used to generate images being immoral if the dataset is not gathered with consent from the artists

Thanks though! App itself looks great. But skipping to use this project as I'm against AI artwork like this

**Comment by Tea23** [comment]
I noticed there is a new icon. Is it still LLM "assisted"?

**Comment by andymandias** [comment]
> I noticed there is a new icon. Is it still LLM "assisted"?

No, see: https://github.com/squidowl/halloy/discussions/998#discussioncomment-13402676

**Comment by Tea23** [comment]
> > I noticed there is a new icon. Is it still LLM "assisted"?
> 
> No, see: [#998 (comment)](https://github.com/squidowl/halloy/discussions/998#discussioncomment-13402676)

Great to see, sorry that I missed that! Thanks! i'm sure the project (based on the contributing guidelines) is happily free of any further LLM bs :)
