### ISSUE TITLE
TOML Config template for easier migration

### ISSUE THREAD

**Issue by chexo3** [squidowl/halloy#476]
I'm currently migrating my config to TOML, it would be really handy if y'all could package a TOML config template that contains every value set to it's default with explanation comments, like with YAML. Then I could copy paste the relevant sections and change them.

**Comment by casperstorm** [comment]
Have you looked at the documentation here? https://halloy.squidowl.org/
It should have all values documented :)

**Comment by chexo3** [comment]
It sure does have every value documented, but having them documented in a config file helps because then I don’t have to switch between a browser window and the config file, and I don’t have to write the boilerplate myself, I can copy it and then adjust it.

I know where the documentation is, I’m saying it was useful to have a template config file before rather than pointing to a giant documentation site and having to go through that.

I’m frustrated that your first assumption was that I didn’t know where the documentation was.
