### ISSUE TITLE
Feature request: Allow nicks to be right-aligned in the main channel buffer

### ISSUE THREAD

**Issue by radge** [squidowl/halloy#477]
As discussed on the #halloy channel, it would be nice if halloy had the ability to right align nicks as I find this improves readability.

Here's a script which does this for irssi: https://github.com/irssi/scripts.irssi.org/blob/master/scripts/nm2.pl

I think it uses the logic of calculating the longest nick then padding each line so that each message starts at the same point.

Here's an example of how it looks in other clients:

![weechat2](https://github.com/user-attachments/assets/7569d9ea-4596-457a-ac98-59721489f525)

**Comment by casperstorm** [comment]
Love this, thanks for the suggestion!

**Comment by KaiKorla** [comment]
Made a short test (incl. isupport.NICKLEN):

![image](https://github.com/user-attachments/assets/52af9ddd-bc7f-486b-a06c-4b282f135281)

Need some more love for the other message cases. I'll could try to go further with this.

**Comment by KaiKorla** [comment]
IMO to fully implement this it is needing some refactoring. Correct me if i am wrong, but the character representation of a message should not be implemented in the data model. The view/widget should decide how it displays a message.

For example: This code https://github.com/squidowl/halloy/blob/d11c1dc170069a557786092017b7e92647b7497f/data/src/message.rs#L574, which is constructing the JOIN message string which is displayed in the buffer, should be moved into src/buffer/channel.rs somehow.

**Comment by casperstorm** [comment]
I think @tarkah is looking into this feature.

**Comment by tarkah** [comment]
In progress :)

![image](https://github.com/user-attachments/assets/10becdaa-fe77-42a1-9d81-0b3b7228f297)

**Comment by casperstorm** [comment]
@radge: This is now merged to main. It will be released along with the next release.
