### ISSUE TITLE
theme filenames don't match names

### ISSUE THREAD

**Issue by dmd** [squidowl/halloy#480]
Many (all?) of the [community themes](https://halloy.squidowl.org/configuration/themes/community.html) with two word names have a dash in the filename (`the-name.toml`), but no dash in `theme = "the name"`.

This means they will not load, as the filename, `theme =` name, and `name =` in the config must *all three* match.

**Comment by dmd** [comment]
Wait but now all the themes on the https://halloy.squidowl.org/configuration/themes/community.html page *no longer work*????

**Comment by casperstorm** [comment]
> Wait but now all the themes on the https://halloy.squidowl.org/configuration/themes/community.html page *no longer work*????

If you run main branch you have to use the themes from main repo. The official wiki isn't published until we make a release. We do this later this week.

**Comment by dmd** [comment]
Yes, sorry, again I forgot to check out the relevant branch.
