### ISSUE TITLE
Cannot type umlaut characters on ANSI macOS keyboard

### ISSUE THREAD

**Issue by cvengler** [squidowl/halloy#493]
Hey,
currently it is not possible for me to type umlaut characters (e.g. [äöü]) on my ANSI macOS keyboard using the ordinary shortcuts that work everywhere else.
Pasting them into the input field works fine.

## Expected behavior

Option + U + [aou] should result in an ä, ö, ü respectively.

## Actual behavior

I only get an a, o, u.

**Comment by casperstorm** [comment]
Hey, thanks for the issue. I believe it is a duplicate of: https://github.com/squidowl/halloy/issues/339.

**Comment by cvengler** [comment]
Yes, it can safely be closed then :)
