### ISSUE TITLE
Channel name is case sensitive

### ISSUE THREAD

**Issue by bmillham** [squidowl/halloy#494]
If you join a channel, say #Rockit and a message is send to #rockit halloy does not display the message.

The channel should not be case sensitive.

**Comment by casperstorm** [comment]
@bmillham, could you show me how to reproduce this, and on which network?
I tried the following on Libera:

Test 1
1. Halloy joins `#FOObaz`
2. Second client joins `#foobaz`
3. Second client sends "hi"
4. Halloy sees "hi"

Test 2
1. Second client joins `#ROCKit`
2. Halloy joins `#rockit`
3. Halloy sends "hi"
4. Second client sees "hi"

**Comment by glguy** [comment]
Libera normalizes channel names. You can't reproduce the bug there.

**Comment by casperstorm** [comment]
> Libera (solanum) normalizes channel names. You can't reproduce the bug there.

That explains. Thank you.

**Comment by gAlleb** [comment]
Hi @casperstorm 

I've encountered this bug too on russian ircnet.ru network.

If you connect to it via ircnet.ru:6688 server and join #usue channel - the channel you've joined will be `#Usue` and you will be able to see only messages from those who are connected to `#Usue` somehow but you'll see full users list.

If you connect to it via irc.386.ru:6688 server and join `#usue` channel - the channel you've joined will be `#usue` and you will be able to see only messages from those who are connected to `#usue` somehow but you'll see full users list.

With all other clients I've tried - there is no such behavior: every message from every user is seen on the channel. Must say it has confused me a lot from the start. But I do think it's connected with how Halloy treats case sensitivity. It joins the same channel butt somehow ignores some messages (the are not visible anywhere).

**Comment by casperstorm** [comment]
Will start looking into this next @gAlleb!

**Comment by gAlleb** [comment]
Thank you!

ircnet.ru doesn't use `Solanum` but historically uses `PTlink` (PTlink7.1.0-rc2). I'm not an expert but I assume that depending on the linked server inside this network it (the server) sends some kind of raw channel data that differs in cases. Maybe not. 

Because when you are inside the network and you `/join #usue` (or `/join #uSUe`) - you end up either on `#usue` or `#Usue` depending on the server you are being connected to. But i'm glad that could catch this cause at the beginning I thought that I'm going mad when I've seen a person talking and talking to himself :)

**Comment by gAlleb** [comment]
> We need to handle this properly which will fix this issue

True. Looking forward. Thank you!

Also if it's possible, it would be really nice if you could share some thoughts and insights on the cause of this bug after the fix. For educational purposes :) Cause it's an interesting issue.

**Comment by gAlleb** [comment]
Same goes for user names sometimes:

<img width="1276" alt="Снимок экрана 2024-10-24 в 19 06 45" src="https://github.com/user-attachments/assets/7224a84f-0d3b-4f8b-a944-b5b7db6a6157">

**Comment by voltagex** [comment]
I can reproduce this with soju - `bouncerserv` vs `BouncerServ`

![image](https://github.com/user-attachments/assets/76a5a2aa-0501-4619-b9fb-92815ce799f2)

**Comment by vk3dan** [comment]
This issue also affects users of the GeekShed network as their servers do not normalise capitalisation of channel names either.
