### ISSUE TITLE
Closing halloy doesn't end the process

### ISSUE THREAD

**Issue by rniii** [squidowl/halloy#497]
This took me a while to notice so I'm not sure in what version this started happening. I use bspwm, and closing the window normally (`bspc node -c`) leaves a process hanging in the background, using a significant amount of memory. I also didn't receive backlogs properly today, which I'm not sure if it was caused by this

Not sure if this is upstream like #284, but there's also another bug where the window doesn't render at all (it becomes fully transparent) until it has mouse focus. I have no idea how to debug that

**Comment by casperstorm** [comment]
@hecrj Have you noticed or seen this before? This is new to me.

**Comment by hecrj** [comment]
This was fixed recently (see https://github.com/iced-rs/iced/issues/2532).

**Comment by casperstorm** [comment]
Thanks for this @hecrj, then this is fixed in main after updating to latest iced: https://github.com/squidowl/halloy/pull/495.

**Comment by rniii** [comment]
Any info on the window not rendering too? I suppose I should open another issue for it

**Comment by andymandias** [comment]
Should be fixed with the release of 2024.11;  feel free to reopen if it's still happening for you @rniii.  And, please do open a new issue for the window not rendering bug, if you're still encountering it with 2024.11.
