### ISSUE TITLE
Notification Sounds

### ISSUE THREAD

**Issue by crftbt** [squidowl/halloy#506]
Halloy 24.07 on NixOS 24.06 (https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=halloy) 

Watching Pulse Audio Volume Control, there don't appear to be any notifications or sounds. What might cause this? 

This is the Halloy notification config below:
```
[notifications.connected]
show_toast = true
sound = "ring"

[notifications.disconnected]
show_toast = true
sound = "dong"

[notifications.highlight]
show_toast = true
sound = "peck"

[notifications.reconnected]
show_toast = true
sound = "squeak"

[notifications.file_transfer_request]
show_toast = true
sound = "whistle"
```

**Comment by andymandias** [comment]
Halloy 24.07 has a different configuration syntax for notifications than Halloy 24.10.  If you're able to upgrade Halloy, then the configuration you've posted should work.  But for Halloy 24.07, you'll want something like:

```toml
[notifications.connected]
enable = true
sound = "message-new-instant"
mute = false
```
