### ISSUE TITLE
Is there a way to wait getting identified before joining channels?

### ISSUE THREAD

**Issue by devantoine** [squidowl/halloy#515]
Everything is in the title.

I'm using basic auth on liberachat.

Should I try connecting using SASL instead?

Thanks for your time :)

**Comment by andymandias** [comment]
There currently is not a way to wait for identification before joining channels.  SASL works better in this regard.  If a channel sends a message that it requires registration, then Halloy will try to join it again after it gets a message that the user has been logged in.  Unfortunately, not all channels send the "requires registration" message and not all servers send the "user has been logged in" message.

**Comment by samkovacs** [comment]
Well, you can just use `on_connect` to identify and join channels. 

`on_connect = ["/msg Nickserv identify PASSWORD","/join #channlel1, #channel2, #channel3"]`

**Comment by devantoine** [comment]
@samkovacs that does not work, channels are joined before being authenticated.

What works though is using SASL, but Liberachat advises against it in favor of TLS.

**Comment by andymandias** [comment]
Libera supports both [PLAIN](https://libera.chat/guides/sasl) and [EXTERNAL](https://libera.chat/guides/certfp) SASL, both of which can be used while also using TLS. If you've turned off TLS to use SASL PLAIN, then it's recommended you turn it back on (by Libera in the linked guide, and less importantly by me).
