### ISSUE TITLE
URL parser choking on Umlauts

### ISSUE THREAD

**Issue by trfunk** [squidowl/halloy#545]
Hello,
the URL parser doesn't seem to handle umlauts at all very well. For example `https://www.reddit.com/r/witze/comments/1fcoz5a/ein_vampir_auf_einem_tandem_gerät_in_eine/` breaks just infront of the ä and sends you to `https://www.reddit.com/r/witze/comments/1fcoz5a/ein_vampir_auf_einem_tandem_ger` when you click it.

If the part infront of the tld contains an Umlaut, the URL is not parsed at all, see `http://öbb.at` (not detected as link),  `http://xn--bb-eka.at/` works, `http://oebb.at/` also works.

Thank you!

**Comment by andymandias** [comment]
I can look at this tonight, yeah.
