### ISSUE TITLE
Change colorscheme to match desktop preference

### ISSUE THREAD

**Issue by 4e554c4c** [squidowl/halloy#555]
Halloy should be able to read whether the desktop is using light-mode or dark mode, and load a theme accordingly. The theme should be able to change while halloy is running. For Linux, it can read dark mode settings from [XDG desktop portal](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.Settings.html) which is supported by most DEs. For Windows/macOS a different solution is needed.

**Comment by casperstorm** [comment]
Currently blocked by https://github.com/frewsxcv/rust-dark-light/issues/29.
Is there any crate which we could consider?
