### ISSUE TITLE
Password command not working for SASL

### ISSUE THREAD

**Issue by heksesang** [squidowl/halloy#580]
According to the documentation, it should be possible to configure `password_command` for `servers.<servername>.sasl.plain`:
https://halloy.squidowl.org/configuration/servers/sasl/plain.html

When I try to do so, I get an error when starting the client that there is no such configuration option, and also looking at the source code I cannot see any such option in the configuration struct.

**Comment by casperstorm** [comment]
@4e554c4c Do you have any insight as you recently added `password_command`?

**Comment by 4e554c4c** [comment]
Yes, this was me mistakingly adding that documentation when the configuration option only exists for servers. It should be pretty easy to add to SASL though

**Comment by casperstorm** [comment]
If you have capacity, and feel like something you want to tackle, then just let me know @4e554c4c.

**Comment by 4e554c4c** [comment]
yep, taking a look :smiley:
