### ISSUE TITLE
Reserved scroll on Mac OS

### ISSUE THREAD

**Issue by devantoine** [squidowl/halloy#588]
On Mac OS, scrolling on the trackpad is reserved.

Meaning scrolling up (two fingers from bottom to top) would scroll the window down, and vice-versa.

Halloy has the opposite behavior, scrolling up on the trackpad scrolls the pane up (meaning we go back in time in the message history).

I'm surprised because I've updated to 2024.12 after not using it for two weeks and just notice this behavior. IIRC it wasn't working like that the version before 🤔

**Comment by casperstorm** [comment]
Iced, the GUI framework we use had a bug which is being fixed in this PR #568 :)

**Comment by casperstorm** [comment]
A fix has been merged to master!
