### ISSUE TITLE
Feature request: Avoid highlighting lines where the user's nickname is part of another word

### ISSUE THREAD

**Issue by zsrv** [squidowl/halloy#590]
If the user's nickname is "thing", and someone uses the word "something" in a channel, that line will be highlighted. It would be nice for Halloy to highlight a line only when an entire word matches the user's nickname.

**Comment by gAlleb** [comment]
It's a great improvement. Just compiled to test it. Thank you @casperstorm 
However if it's all right I'd like to propose some minor changes if they are possible.

Say your nick is `Thing`. In `2024.12` the behavior is:
1. `Thing` - nick is highlighted, notification is enabled
2. `thing` - nick is `not` highlighted, notification is `not` enabled
3.  `everyotherThing,` - nick is highlighted, notification is enabled
4.  `everyotherthing:` - nick is `not` highlighted, notification is `not` enabled

With this https://github.com/squidowl/halloy/pull/597 the behavior is:
1. `Thing` - nick is highlighted, notification is enabled
2. `thing` - nick is highlighted, notification is enabled (In `2024.12` it was neither highlighted nor enabled).
3.  `everyotherThing` - nick is `not` highlighted, notification is `not` enabled - `GREAT!`
4.  `everyotherthing` - nick is `not` highlighted, notification  is `not` enabled - `GREAT!`
5.  `Thing:` - nick is `not` highlighted, notification is `not` enabled - `NOT GREAT!`
6.  `thing,` - nick is `not` highlighted, notification is `not` enabled - `NOT GREAT!`

What I'd like to propose for your consideration is to allow only some characters be part of the nick and still be highlighted and enable notification:
1. `Thing,`
2. `Thing.`
3. `Thing:`
4. `thing,`
6. `thing.`
7. `thing:`
8. `! ? ...`
9. you see my point 😄 
10. Case sensitivity is debatable but I think it's ok to have both registers work as they do now.
