### ISSUE TITLE
Feature Request: Allow changing the mouse scroll direction

### ISSUE THREAD

**Issue by zdzielinski** [squidowl/halloy#593]
Right now, I see no way to change the mouse scroll direction in the configuration settings.

Allowing this as a changeable feature would be great, as `halloy` uses the opposite scrolling direction that I use normally.

**Comment by tarkah** [comment]
I'm pretty sure the reversed scroll direction was a bug with iced, our gui framework. Can you run off master and see if it's fixed? We recently updated iced which fixed this issue.

**Comment by zdzielinski** [comment]
You are correct, I just ran off `main`, and it looks like the scrolling direction is "normal".

Knowing that most scroll directions are configurable at the OS level (MacOS natural scrolling, etc), this issue can most likely be closed. Seeing as how this wasn't a "flavor choice" of halloy as I first thought, I do not see the need for this to be configurable at the application level.

**Comment by tarkah** [comment]
Glad it's fixed and agreed 👍
