### ISSUE TITLE
Window appears lagging when resizing

### ISSUE THREAD

**Issue by casperstorm** [squidowl/halloy#60]
Noticed a release build on my Windows machine acted quite laggy. Maybe advanced text?

https://github.com/squidowl/halloy/assets/2248455/39fa1269-d2b4-4045-bf88-e1c7c94c82e3

**Comment by tarkah** [comment]
Does this happen if you disable advanced text?

**Comment by tarkah** [comment]
Interesting. I don't see this issue on Linux.

**Comment by casperstorm** [comment]
Neither do I on macOS - only on my Windows machine.

**Comment by ineeee** [comment]
i can confirm, also happens on my machine. is there a way for me to switch between iced's different rendering engines? maybe it happens on vulkan but not on opengl?

**Comment by tarkah** [comment]
> i can confirm, also happens on my machine. is there a way for me to switch between iced's different rendering engines? maybe it happens on vulkan but not on opengl?
> 

You can try ICED_BACKEND=tiny-skia for the software renderer

**Comment by ineeee** [comment]
tiny-skia is so much worse, as laggy as the video in the OP

**Comment by ineeee** [comment]
today i noticed that only horizontal resizing is laggy, vertical is perfectly smooth. text wrapping is slow maybe?

**Comment by casperstorm** [comment]
Closing in favor of #135
