### ISSUE TITLE
Sounds not available in Flatpak

### ISSUE THREAD

**Issue by distefam** [squidowl/halloy#604]
I installed Halloy via Flatpak (version 2024.12) and the intended sounds directory is empty: `$HOME/.var/app/org.squidowl.halloy/config/halloy/sounds/`

**Comment by casperstorm** [comment]
Sounds folder is for your own sounds, it will always initially be empty.

Halloy has a few built in sounds which you can see here: https://halloy.squidowl.org/configuration/notifications.html#sound.
