### ISSUE TITLE
Theme reset on config reload if dark/light themes configured

### ISSUE THREAD

**Issue by 4e554c4c** [squidowl/halloy#617]
# Config

```
[theme]
light = "base16-atelier-forest-light"
dark = "base16-rose-pine-moon"
```

# Steps to reproduce

1. Open Halloy
2. click 'reload config'
3. Theme should now be "Ferra" and neither of the above themes.

**Comment by casperstorm** [comment]
As discussed on IRC. I can't reproduce this on Windows nor macOS.
Perhaps a Linux issue 🤔
