### ISSUE TITLE
High CPU usage - macOS

### ISSUE THREAD

**Issue by alanskind** [squidowl/halloy#637]
<img width="493" alt="image" src="https://github.com/user-attachments/assets/6e5b4abf-23b0-4c48-a566-96786d213d00">

macOS 14.6.1

The latest version of halloy.

**Comment by THeK3nger** [comment]
Yep, I have the same issue. It is stuck at 140% CPU.

**Comment by casperstorm** [comment]
I can reproduce this as well, will start digging into what has happened. Sorry for the troubles.

**Comment by casperstorm** [comment]
I found the error and is pushing out a `2024.14` now.

**Comment by casperstorm** [comment]
https://github.com/squidowl/halloy/releases/tag/2024.14
