### ISSUE TITLE
Halloy disconnects if app left in background

### ISSUE THREAD

**Issue by gurgl** [squidowl/halloy#655]
I'm running ubuntu 24.04 using Wayland.  If I leave Halloy for a while and then Alt-Tab back to it, it will have disconnected me. As if some thread is suspended while the app is not having focus?

**Comment by tarkah** [comment]
What version of Halloy?

**Comment by gurgl** [comment]
Sorry, missed this. I'm pretty certain this issue sorted itself after last upgrade so closing this one.
