### ISSUE TITLE
User name autocomplete

### ISSUE THREAD

**Issue by lodenrogue** [squidowl/halloy#69]
It would be nice to press tab and have the application autocomplete a matching username when typing in a channel.

**Comment by casperstorm** [comment]
Yes! This is something we need to add. I am missing it my self as well.

**Comment by lodenrogue** [comment]
I'm working on a solution for this

**Comment by Tangdongle** [comment]
Hey @casperstorm , I've had a crack at this, PR is here: https://github.com/squidowl/halloy/pull/93. I can't say that I 100% grok the Iced workflow, so open to suggestions and corrections!
