### ISSUE TITLE
Advanced server config

### ISSUE THREAD

**Issue by tranzystorek-io** [squidowl/halloy#72]
I wanted to give `halloy` a spin but my current irc configuration requires a "Server password" to authenticate over at my bouncer, which the config template seems to be missing.

**Comment by dvtkrlbs** [comment]
Also I've been wondering about certificate based nickserv authentication. Is it supported and if not how could a support for it could be added. I am down to try to implement it?

**Comment by casperstorm** [comment]
You can find all server fields here: https://docs.rs/irc/0.15.0/irc/client/data/config/struct.Config.html#fields.
For `Server Password` you simply use `password`.

**Comment by tranzystorek-io** [comment]
@casperstorm thank you!

**Comment by casperstorm** [comment]
> @casperstorm thank you!

You are welcome, did it work for you?

**Comment by tranzystorek-io** [comment]
yes, connected no problem :3
