### ISSUE TITLE
Add clickable hyperlinks that open in a user's browser

### ISSUE THREAD

**Issue by playonverbs** [squidowl/halloy#75]
URLs within chat windows could have an underline text effect applied when hovered over with the mouse cursor and when clicked these could be opened by an application chosen by the operating system.

The [open](https://crates.io/crates/open) crate could be used to accomplish this.

**Comment by tarkah** [comment]
I've marked this issue as `upstream`. We are 100% looking to support this but we're blocked by [iced](https://github.com/iced-rs/iced) not supporting `rich text` yet which makes this hard to achieve in an optimal manner (without breaking text wrapping).

The good news is `rich text` shouldn't be too far out, so this is on the horizon.

**Comment by ColinMcKechney** [comment]
Just bumping this to ask we're still waiting on [iced](https://github.com/iced-rs/iced) to implement `rich text` or if it's something we could add in the near future?

**Comment by casperstorm** [comment]
Unfortunately still blocked, maybe @hecrj has an update on when rich text is coming to iced?

**Comment by hecrj** [comment]
@casperstorm @ColinMcKechney Rich Text is in [the roadmap](https://whimsical.com/roadmap-iced-7vhq6R35Lp3TmYH4WeYwLM) and planned for the next release.

I can't give a specific time frame, but it's coming soon™.

**Comment by superlou** [comment]
Would it be too much of an antipattern to temporarily detect the first URL in a message and open it when you click on a message?
