### ISSUE TITLE
notify on tls error

### ISSUE THREAD

**Issue by ineeee** [squidowl/halloy#76]
currently a connection fails silently when connecting to a server with an invalid tls certificate. its possible to read the error in the `config/halloy.log` but its not user-friendly.

it would be an improvement to show an error in the window mentioning why it failed to connect.

environment: windows 10, halloy 23.1-alpha1, own irc server with self-signed cert.

**Comment by casperstorm** [comment]
Thanks, I'll look into that. 
If you want to accept a invalid cert you can use: `dangerously_accept_invalid_certs: true`
