### ISSUE TITLE
the last word disappears sometimes

### ISSUE THREAD

**Issue by ineeee** [squidowl/halloy#81]
when some lines in the text reach a certain length, the last word seems to disappear. i noticed this when someone said `pentile` which led to the message `[21:12:34] <someone> ` in halloy, but `[21:12:34] <someone> pentile` in hexchat.

i tried repeating the word pentile with 1 to 10 characters before it and this happened:
![image](https://github.com/squidowl/halloy/assets/10874672/dd3b51f9-9174-4481-9fee-2e3429eb78e4)

i kept removing characters and couldn't reproduce:
![image](https://github.com/squidowl/halloy/assets/10874672/70bc08e2-ca68-4156-aac0-cbeb27f9e451)

however it happens again with "pe" and "p":
![image](https://github.com/squidowl/halloy/assets/10874672/05422f5b-9de3-4481-80d7-1a6e03883853)

sorry. what? i dont even know what is happening here. how do i even begin figuring this out lol?

**Comment by ineeee** [comment]
i wrote this bash script to test it out:
```bash
for word in a ab abc abcd abcde; do for i in $(seq 0 9); do for j in $(seq 1 $((i+1))); do printf "%d" $i; done; printf " %s\n" $word; done; done
```

i copypasted and sent it:
![image](https://github.com/squidowl/halloy/assets/10874672/3e4cdada-c707-4f34-b107-1be92d52a1a9)

indeed, "a" and "ab" disappear. wut?

**Comment by ineeee** [comment]
i'm unable to reproduce this with the default font size of 13:

![image](https://github.com/squidowl/halloy/assets/10874672/9e363363-03f4-4a82-831f-e49d3ea4d767)

**Comment by tarkah** [comment]
This should be fixed upstream by https://github.com/iced-rs/iced/pull/1921

We need to update our iced fork to capture this change, I'll do that this week.

**Comment by ineeee** [comment]
i'm happy to see a fix so quickly! thank u
