### ISSUE TITLE
Save chatroom archive

### ISSUE THREAD

**Issue by altilunium** [squidowl/halloy#82]
Is there a feature to save a specific chatroom archive to a .txt file?

**Comment by lodenrogue** [comment]
I think chat logs are currently saved as zlib in the halloy/history directory. What OS are you on?

If you're on macOS you can run the following command:

```
cat filename | perl -MCompress::Zlib -E 'undef $/;print uncompress(<>)'
```

**Comment by altilunium** [comment]
I am currently using Windows.

I am attempting to decompress the zlib file using Python. However, it appears that I have encountered an encoding error.

```python
import zlib

def decompress_file(input_file, output_file):
    with open(input_file, 'rb') as f_in, open(output_file, 'wb') as f_out:
        compressed_data = f_in.read()
        decompressed_data = zlib.decompress(compressed_data)
        f_out.write(decompressed_data)

# Usage example
input_file_path = '17597157479094131989'
output_file_path = 'decompressed_file.txt'
decompress_file(input_file_path, output_file_path)
print(f"File decompressed successfully to: {output_file_path}")
```

![image](https://github.com/squidowl/halloy/assets/70379302/de165b60-2683-42a6-96c0-888394cf7d5b)

**Comment by tarkah** [comment]
> I am currently using Windows.
> 
> I am attempting to decompress the zlib file using Python. However, it appears that I have encountered an encoding error.
> 
> ```python
> import zlib
> 
> def decompress_file(input_file, output_file):
>     with open(input_file, 'rb') as f_in, open(output_file, 'wb') as f_out:
>         compressed_data = f_in.read()
>         decompressed_data = zlib.decompress(compressed_data)
>         f_out.write(decompressed_data)
> 
> # Usage example
> input_file_path = '17597157479094131989'
> output_file_path = 'decompressed_file.txt'
> decompress_file(input_file_path, output_file_path)
> print(f"File decompressed successfully to: {output_file_path}")
> ```
> 
> ![image](https://github.com/squidowl/halloy/assets/70379302/de165b60-2683-42a6-96c0-888394cf7d5b)
> 
> But at least, all the text is readable by using utf-8. I can manually clean it later.

We don't encode in plaintext. We use bincode encoding and are persisting internal data structures to halloy.

Instead of trying to work with these files, it'd be better if a separate issue was opened for exporting history as plaintext

**Comment by lodenrogue** [comment]
Yeah, I created one here: https://github.com/squidowl/halloy/issues/91
