### ISSUE TITLE
Smart join message filter

### ISSUE THREAD

**Issue by Chemiseblanc** [squidowl/halloy#94]
It would be nice to have functionality similar to [weechat](https://blog.weechat.org/post/2008/10/25/Smart-IRC-join-part-quit-message-filter) where join/part/quit messages are only displayed if the user has spoken in a channel within some period of time.

**Comment by casperstorm** [comment]
This seems like a nice third way of handling parts/join/quit.

I see it as a enum of 3 different variants a user can choose from:

1. All
2. None 
3. Smart(Time)

**Comment by lodenrogue** [comment]
Can we make All the default behavior though?

**Comment by casperstorm** [comment]
> Can we make All the default behavior though?

Yes.
